### ISSUE TITLE
Unable to access to "Unique players" tab in the "Online Activity" category

### ISSUE THREAD

**Issue by Aurelien30000** [plan-player-analytics/Plan#1015]
### Describe the bug

I think it's caused by my french translation but i inform you anyway -> I can't access to this menu : ![Capture](https://user-images.githubusercontent.com/43724816/56699409-9b4c4b80-66f5-11e9-9a38-248bcf197bfa.PNG) (Joueurs Unique(s)S or Unique Players)
No errors in particular (logs, debug page)
If you need HTML files, ask me ^^.

I also take the opportunity to report you the presence of an extra 'S' at the end of this text not coming from my translation.

Thank you in advance :)

### Server information

Last version of Plan (Dev 4.8.2), Paper-Spigot 1.12.2 or 1.13.2 last build linked with WaterFall 1.14 - build 279.

### Exceptions & Other Logs

No

### Additional information

No

### Frequency of occurrence
Always with my translation active.

**Other:** No

**Comment by Rsl1122** [comment]
The extra S seems to come because the translation for UNIQUE_PLAYERS contains the word *UNIQUE*, and because the translation for html is kinda just tacked on, another entry `HTML - UNIQUE                                   || UNIQUE(S)` does a second pass on the translated part. 

I resolved both issues by removing (x) from the end of `Nouveau(x)` and (S) from `UNIQUE(S)` - I hope that is a viable solution
