### ISSUE TITLE
Make the base URL more customizable

### ISSUE THREAD

**Issue by oleterno** [plan-player-analytics/Plan#1067]
### My problem
I am hosting the Plan web interface behind a proxy server and want to make it accessible with `https://www.example.com/plan`. However, if I try to reach the interface with that url, it rewrites the url ending from `/plan` to `/server`, which will not reach the interface. The correct url would be `https://www.example.com/plan/server`. 

I set the `Address: example.com/plan` in `config.yml` and this made the interface accessible from `https://www.example.com/plan/server`, but links from placeholders still have the issue of pointing to i.e `/server` instead of `/plan/server`. I forked the repository and went in and edited the placeholders in the code to make the links right (for my unique case) but I think there should be a better solution to this.  

### A possible solution 
I would like to be able to change the base url of the web server and for the placeholders to use the base url in their links. Could this be a toggleable feature in `config.yml`?

**Comment by Rsl1122** [comment]
Could you post a link to an example point in code where the placeholders use the wrong address? :)

**Comment by oleterno** [comment]
Certainly, I can also post this for all the files I changed to make it work for me.

![image](https://user-images.githubusercontent.com/35765519/59111067-9c050e00-8940-11e9-9282-0cc11e2b1670.png)

**Comment by oleterno** [comment]
They should all be visible here: https://github.com/oleterno/Plan/commit/0b04b78a8f38daf1d2a365298871ac072a6eb79e

**Comment by Rsl1122** [comment]
I don't think this should be implemented because only a small portion of servers use a proxy with subdirectory in the address, subdomains are a more common approach.

Currently the parts of code that do redirecting and other address related things are all over the codebase with some using different approaches (302 response header, placeholder links, hardcoded links, links in commands, address in the database) - An unified approach might not be easy to implement.
