### ISSUE TITLE
Invalid playername on web interface [when translated]

### ISSUE THREAD

**Issue by haeiven** [plan-player-analytics/Plan#1092]
### Describe the bug

On the web interface, a player called _NewFace_, is renamed to _NouveauFace_ when using french translations.

![playername](https://user-images.githubusercontent.com/11612016/60806126-773fc880-a182-11e9-8789-d35811f63fd8.png)

### Server information

Paperspigot 1.8.8 / Latest Plan version

### Exceptions & Other Logs

/

### Additional information

**Frequency of occurrence**: <> /

**Other:** /

**Comment by Rsl1122** [comment]
This is due to how the translation of web pages is handled - original text is replaced with the translated version.
One of the translation lines is "New" for "New players".

Unfortunately it is not possible to distinguish between different instances of the same word, so all instances are replaced (as seen here)

----

One way to solve this is by changing the code for what the text being replaced is - from "New" to "New " for example.
