### ISSUE TITLE
advancedban status

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1135]
### Describe the issue
The status of AdvancedBan shows that the person is not banned, but the player is banned according to AdvancedBan so plan is not showing warnings and bans correctly

### Server information
PlanVersion : 4.9.2
BungeeVersion: Build 1419
AdvanedBan Version : 2.1.5

### Exceptions & Other Logs
I hoped that plan registed the ban in advancedban and updated this in the player base.

### Additional information
Plan Status : https://i.imgur.com/4b5oheh.png
AdvancedBan status : https://i.imgur.com/jCHlhjT.png

**Comment by Rsl1122** [comment]
Looks like a simple leave listener is not enough in this case. I'll see if I can hook into some ban event of some kind.

Cropped screenshots out of imgur since their service does not work properly on mobile

![image](https://user-images.githubusercontent.com/24460436/62838275-97cbd880-bc82-11e9-9c14-2937c08231f8.png)
![image](https://user-images.githubusercontent.com/24460436/62838276-9e5a5000-bc82-11e9-968d-824d9f18dbdb.png)
