### ISSUE TITLE
cmi alias

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1136]
### I would like to be able to..
I will be nice if there is a option to see what variable is used with the CMI command.
For example the command CMI is being used 129921 times.
And there is no furter information about what sub command is used.

so i think it will be nice to capture the first variable after that for example
cmi home
cmi warp
cmi back
and so on.

So only the first variable that is given by the player everything after that is garbage.

**Comment by Rsl1122** [comment]
I agree, command usage in its current state is pretty much useless. (This is why the current version will be removed with interface redesing #1021)

I have yet not decided how or if it will be brought back afterwards in some new form, but if I decide to do so I'll keep this suggestion in mind.
For now this is marked out of scope due to the future removal.
