### ISSUE TITLE
Make default bungee and bukkit configs use the same database type

### ISSUE THREAD

**Issue by CamronW** [plan-player-analytics/Plan#1199]
Currently the default database types are:

Bungee: MySQL
Bukkit: SQLite

I think changing the Bukkit default to MySQL also would help save some trouble. I ran into issues in my setup process because I wrongly assumed the default Bukkit config would follow the Bungee one.

**Comment by Rsl1122** [comment]
The default database on Bukkit uses sqlite since it is a file based database and needs no configuration to work. This allows servers that don't use Bungee easier install. 

Bungee needs Mysql so that multiple servers can use the same database (It's more difficult to pull off with a file based database) - Setting Mysql as default on bukkit would cause Plan on these servers to fail to enable on first boot. 

I'll add a notice on the Bungee set up to change the `Database.Type` to Mysql on the bukkit servers. 

I get where this is coming from but current configuration is better for solo server installations.
