### ISSUE TITLE
Duplicate lines of region claims

### ISSUE THREAD

**Issue by yaroslav4167** [plan-player-analytics/Plan#1206]
![claims list](https://user-images.githubusercontent.com/18057310/67610737-01915400-f795-11e9-9b9e-212b25af05ee.png)
Plan: 5.0-build-260
SpongeForge: 1.12.2-2838-7.1.7-RC3928
GriefPrevention: 1.12.2-4.3.0.692

**Comment by Rsl1122** [comment]
I have opened a new issue over on GriefPrevention Sponge port repository, as it would seem that the issue is not caused by code.

Please post any extra information (Listings of claims given by the plugin for example) in the issue above. Also make sure that the player has not created duplicate claims in the same location.
