### ISSUE TITLE
Relogging should not count as a new session [change Session length average to median]

### ISSUE THREAD

**Issue by skerit** [plan-player-analytics/Plan#1234]
### Is your feature request related to a problem? Please describe.

I have a few players that have occasional lag issues (because of crappy wifi or so), they think they can fix it by logging out and directly logging in again, but this seriously skews the "session count" statistic

### I would like to be able to..

If a player leaves and comes back within a minute or so, it should just count as 1 single session.

**Comment by Rsl1122** [comment]
The way current playtime data is implemented is that there are 3 numbers: `session_start`, `session_end` and `afk_time`.

If two sessions that have < 60 seconds between them would be combined, either the way playtime is stored would need to be changed, or the playtime statistic would become unreliable.

Because a lot of queries depend on the current playtime calculation, I think implementing this would take a lot of effort for a small gain.

----

Do you think it would be possible to work around this issue in some other way? I think the current implementation where *each login-play-logout is a session* is technically true

**Comment by skerit** [comment]
Yeah, it's technically true, but now I have a player who has 257 sessions, while the number two has "only" 97, so her sessions make the average session count (and average session length) also unreliable. Maybe it would help if sessions under 60 seconds would just be ignored for the averages?

**Comment by Rsl1122** [comment]
Ignoring extremely short sessions to fix length averages would make sense - A median might make more sense for session count average without needing to ignore short sessions from the count.

This would solve some issues that come from this without combining sessions (as that is a bit problematic and someone could use repeated short sessions as a metric for connection issues.)
