### ISSUE TITLE
Feature Request: Do not require user password login when HTTPS is enabled

### ISSUE THREAD

**Issue by database64128** [plan-player-analytics/Plan#1264]
### Is your feature request related to a problem? Please describe.

It makes no sense to enforce user password login when HTTPS is enabled. Besides, current implementation uses HTTP basic authentication, which is arguably far behind from modern security standards.

For my own server, I put Plan behind a reverse proxy. I followed the documentation to change the `Webserver/Security/SSL_certificate/KeyStore_path` setting to `proxy`. This automatically enabled password authentication. But I also want everyone to be able to visit without password.

My friend's server also uses Plan (recommended by me). He also put Plan behind a reverse proxy but he didn't change the setting in Plan's configuration file. It works and doesn't require password login.

Apparently after fixing #1207 & #1210 it is no longer necessary to change the `Webserver/Security/SSL_certificate/KeyStore_path` setting to `proxy`.

### I would like to be able to..

Password login should be separated from SSL/TLS settings as an independent option. It should default to no.

Also update related documentation to reflect current implementation regarding reverse proxy.

And I'd like to thank you for your GREAT work on Plan! Among the mods and plugins I've used, Plan has the best documentation, best support from author, and is the most actively maintained plugin. 🎉👍

**Comment by Rsl1122** [comment]
Thanks for a clean request. 

Making this a setting has been on my radar for a while, but I haven't gotten around to doing it because of following ~~reasons~~ excuses: 

- I don't know how tightly coupled the login is to https in the code
- I want to avoid situation where login option exists with servers that don't have https because that will lead to people to ask why their login is not enabled without https (even if it says that https is required above it)
  - (It will also lead to feature request for login without https)
  - (I get that setting up https is a big pain, but I think it is better to force people to have it for security than giving people false sense of security.)

That said it's probably good to do this sooner than later.

**Comment by viet** [comment]
I'm willing to pay for this feature to be done fast

**Comment by Rsl1122** [comment]
Added a new setting `Webserver.Security.Disable_authentication` that allows running HTTPS without Plan doing login. I think the name of the setting when set to false still implies that authentication is not necessarily enabled.

This setting defaults to `false` to avoid exposing previously secured webservers by accident.

Implementing this setting turned out to be pretty straightforward, as there was already a method called `isAuthRequired`.

----

Please send an amount you deem appropriate to https://www.paypal.me/Rsl1122

Dev build of above commit [Plan-5.0 dev build 377.jar.zip](https://github.com/plan-player-analytics/Plan/files/4091530/Plan-5.0.dev.build.377.jar.zip)
