### ISSUE TITLE
GeoLocation table with IP-Address

### ISSUE THREAD

**Issue by TastaMax** [plan-player-analytics/Plan#1275]
### Is your feature request related to a problem? Please describe.

The IP address is not saved in the database for the table geolocations.

### I would like to be able to..

to see the IP address in the DB for better identify people when he try to join the server again

**Comment by Rsl1122** [comment]
Hey, thanks for the idea. I'll unfortunately have to pass on implementing it.

Anonymized IPs were removed in 5.0 because having the first 2 parts of the IP is not enough for identifying two people playing from same location and so having them on the page was not useful. 

IPs are personal data according to [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) - Removing the IPs entirely means Plan doesn't have personal data and I don't have to deal with the relatively high amount of requests to change how IPs are shown/used/stored/managed.

----

You can use [AltFinder](https://github.com/egg82/AltFinder) or similar plugin to detect alts.
