### ISSUE TITLE
Possible crash with getting placeholder data from database

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1322]
### Describe the issue
I created a custom text with the plugin CMI to show some Plan placeholders, however sometimes when you do the command the server overloads and basically has to be force closed to restart it. I'm guessing its probably some overload with getting the data from the plan database.

### Server information
Paper(89)
Minecraft 1.15.2
Plan 5.0 build 382

### Exceptions & Other Logs
https://hastebin.com/wuzerapani.md

**Comment by Rsl1122** [comment]
You need to perform the placeholder replacement asynchronously if you use Plan placeholders.

**Comment by DrakePork** [comment]
How does one run the placeholder replacement async?

**Comment by Rsl1122** [comment]
To run the code async `the code` needs to run a task with the Bukkit Scheduler asynchronously.

This is unfortunate as most plugins give placeholders for data that is already in memory, but Plan can not do so because none of the interesting data is in memory when the request is made (most of the placeholders need some data analysis).

This means that most plugins do the placeholder replacement on the server thread, and database connection blocks the server thread which can lead to the server shutting down because it was not responding - only plugins that run a task asynchronously are not affected.

**Comment by DrakePork** [comment]
Mkay
