### ISSUE TITLE
It's not a valid YAML

### ISSUE THREAD

**Issue by luluxe** [plan-player-analytics/Plan#1363]
### Describe the issue
The config.yml is not a valid Yaml and i cannot parse with others components

### Server information
Plan 5.0 build 415

### Exceptions & Other Logs
My library in PHP symfony/yaml cannot parse and print : A colon cannot be used in an unquoted mapping value at line 70 (near "    Unit: SECONDS")

### Additional information
It's very boring to have not valid yaml because i can't parse it in order to modify it.

**Comment by AuroraLS3** [comment]
### TODO

- Change the config to fit the specification
  - Modify yml to fit the specification
    - Move true/false settings to Setting.Enabled
    - Move Time unit numbers to Setting.Value
  - Write the changes to ConfigUpdater to apply the changes to old configs
  - Change the paths of the affected Settings (Java)
  - Modify TimeSetting to look at Setting.Value instead of Setting for the number
- Prepare for configurate
  - Extract interface from Config and ConfigNode, (keep implementation with classes LegacyConfig and LegacyConfigNode)
  - Extract interface from and rename ConfigReader and ConfigWriter to LegacyConfigReader and LegacyConfigWriter
- Write configurate based Config implementation
  - Add configurate as a dependency, shadow and relocate it
  - Implement ConfigNode and Config interfaces with configurate
  - Move everything that extends LegacyConfig to use ConfigurateConfig
    - Optional: If it is easier, change the configs to use composition instead of inheritance
  - Implement ConfigReader and ConfigWriter and writer for configurate.
  - Implement a ConfigReader and ConfigWriter that pass the read/write call to appropriate implementation
    - eg: If ConfigurateConfigReader fails to read the yml (Because it is not valid yml), read with LegacyConfigReader so that the modifications mentioned above can be applied.
    - eg: If Writer is passed a LegacyConfig it is written with LegacyConfigWriter
    
----

### Acceptance criteria

At the end of this following classes should exist:
- Config (interface)
- ConfigNode (interface)
- ConfigWriter
- ConfigReader
- LegacyConfig
- LegacyConfigNode
- LegacyConfigWriter
- LegacyConfigReader
- ConfigurateConfig
- ConfigurateConfigNode
- ConfigurateConfigWriter
- ConfigurateConfigReader
- _____ConfigReader (the reader that calls other readers)
- _____ConfigWriter (the writer that calls other writers)

Validations:
- Plan can enable with an old config (I think there is an unit test for this)
- Old config is transformed during enable
- Transformed yml is valid yml
- Config does not lose comments when using configurate
- Plan can enable with a new config without using LegacyConfig

**Comment by AuroraLS3** [comment]
Next version will modify config to be valid yaml. (dev build https://github.com/plan-player-analytics/Plan/actions/runs/2641648189)

I split the configurate stuff to another ticket since it seemed unrelated extra work for this ticket.
