### ISSUE TITLE
Ingame Playtime Check

### ISSUE THREAD

**Issue by Exophobias** [plan-player-analytics/Plan#1384]
### Is your feature request related to a problem? Please describe.

No, rather than giving out the entire stats page address. It'd be nice to have a /playtime command to show the Total, Active, and AFK playtime instead of opening a browser window.

### I would like to be able to..

Have players with appropriate permissions do /playtime or some command that will give the Total, Active, and AFK time for the command sender's UUID rather than sending them to their player page.

**Comment by Rsl1122** [comment]
Does `/plan qinspect` have these?

**Comment by Exophobias** [comment]
It only includes total time, but that command is the info I am looking for, just would be nice with the added variables.
:)

Thanks

**Comment by mcqwy** [comment]
Can you provide API interface while implementing this function?
I'm developing an online duration reward plug-in, and I need this API.

**Comment by Rsl1122** [comment]
@mcqwy See if https://github.com/plan-player-analytics/Plan/wiki/APIv5-Query-API sorts the need, there are some pre-made queries available

**Comment by mcqwy** [comment]
I'm sorry! My English is not very good.
I can't understand your code comments.
`long fetchPlaytime(UUID playerUUID, UUID serverUUID, long after, long before);`
For example:
I want to get the duration of the online time of the players of AAAA today.
How can I fill in after and before parameters?

The most important one is: I found that when the players are offline, today's data will appear.
That is to say, when the player goes online for the first time today, when I call your API, I may not get the online time of the player today.

I found that players' online time today may be stored in thread memory.
Then store when the player leaves the server.
Can you make an API callback interface for other developers to call players' online hours today?

I still want your plug-in to store data every time a player goes offline.
I agree that data is not stored in real time, because it will consume server performance.

**Comment by Rsl1122** [comment]
Yep the stuff you said is true @mcqwy .
I can add a method for getting the online playtime while keeping the current method as is.

`after` and `before` are Unix time (milliseconds) since 01.01.1970, so if you have a specific time you want you can use `long after = System.currentTimeMillis() - TimeUnit.DAYS.toMillis(1);` (as an example)
Any sessions inside `after` and `before` is counted. - So if you needed all data, you would call `fetchPlaytime(playerUUID, serverUUID, 0L, System.currentTimeMillis())`

**Comment by mcqwy** [comment]
When the method is implemented.
Please let me know.
And tell me in which version it has been implemented.
Thank you!

**Comment by mcqwy** [comment]
`time = XXXX-XX-XX 00:00:00`
`after = sd.parse(time).getTime();`
`long i = queryService.getCommonQueries().fetchPlaytime(player.getUniqueId(), queryService.getServerUUID().get(), after, System.currentTimeMillis());`
Hello, I'm trying to use the method to query the player's online time today.
My method is not correct. Can you tell me why?
How can I get the player's online time correctly？

**Comment by Rsl1122** [comment]
- Make sure your SimpleDateFormat has the correct format on in (It is not shown in your code so I can't tell)
- `i` is in milliseconds, so make sure to format that appropriately

Otherwise looks good to me. If you have mupltiple servers in your network you might need to use https://github.com/plan-player-analytics/Plan/blob/master/Plan/api/src/main/java/com/djrapitops/plan/query/CommonQueries.java#L65 to get the playtime on all servers of the network

> How can I get the player's online time correctly？

If the player is online at the moment, you will also need to call `CommonQueries#fetchCurrentSessionPlaytime`, see the Javadoc for return value: https://github.com/plan-player-analytics/Plan/blob/master/Plan/api/src/main/java/com/djrapitops/plan/query/CommonQueries.java#L54

**Comment by mcqwy** [comment]
![1234](https://user-images.githubusercontent.com/38318368/89454581-7d441680-d793-11ea-8b02-dff52cb7c761.png)
I can't get the method at the red mark

**Comment by Rsl1122** [comment]
Hmm, maybe the api artifact is out of date on the repository - I'll try updating it tomorrow, I'll let you know here when I've done so.

**Comment by mcqwy** [comment]
Well, thank you very much.

**Comment by mcqwy** [comment]
How can I call the current API to get the player's online time today？

**Comment by Rsl1122** [comment]
Your method looks correct to me.

**Comment by mcqwy** [comment]
Previously, I used the above method to get the player's online time, but it didn't work.
Is my version too old?

**Comment by Rsl1122** [comment]
In what way does it not work?
