### ISSUE TITLE
Plugin CPU/RAM usage

### ISSUE THREAD

**Issue by MrRockis** [plan-player-analytics/Plan#1391]
I would like to have every plugin in the plugins tab, and not only the officially supported ones. It would be cool if you could see cpu & ram usage of all plugins under the plugins tab. It would be like deprecated plugin "toplite", but online and for each server.

**Comment by Aurelien30000** [comment]
I think It's a complex operation to monitor that, use timings or spark plugin instead, because you don't need to check and store these information everytime 🤔

**Comment by Rsl1122** [comment]
I looked into it and it would need sampling all threads similar to spark plugin, mapping each class to a plugin and then calculating total CPU usage somehow from those.

Seems like an idea for a plugin separate from Plan - Implementing this to Plan would be a big hassle mostly because of the class mapping (I know it's doable on Spigot, but how about other platforms like Bungee, Sponge etc).

Closing as out of scope due to complexity of the feature.
