### ISSUE TITLE
Can you add fabric support to it？

### ISSUE THREAD

**Issue by XinKerrr** [plan-player-analytics/Plan#1414]
Hi,This plugin is great, but can it support the information display of the subserver as the fabric server, just like the paper plugin.

**Comment by Rsl1122** [comment]
Bukkit, Spigot and Paper are coded on top of the Minecraft sever so that the plugin devs don't need to worry about the Minecraft server code.

Fabric however is for making mods, and requires Minecraft server as a dependency. It also does not provide enough events that the other server APIs provide.

Because of these limitations fabric support would be too much work to maintain (Updates for every version similar how spigot etc need to do it).

**Comment by XinKerrr** [comment]
OK, I see. Anyway, this plug-in is really awesome. Thank you

**Comment by XinKerrr** [comment]
Ohhh, brother, I found an extremely interesting thing that can be compatible with almost all servers of the higher version of minecraft at the same time. It can be compatible with paper, bungee, waterfall, vanilla, etc., and it also provides corresponding APIs. I hope you can learn more about it

**Comment by XinKerrr** [comment]
https://github.com/Fallen-Breath/MCDReforged

**Comment by Rsl1122** [comment]
The linked api appears to use python and Plan is written in Java.

While it is possible to call Java code from python, their plugin api doesn't go very deep into the server code - the events are only displayed for the activity that appears in the console logs for example.
