### ISSUE TITLE
Graphs and adblock

### ISSUE THREAD

**Issue by evanmn** [plan-player-analytics/Plan#1445]
### Is your feature request related to a problem? Please describe.

Many people use adblockers today and a common list is the [easylist](https://easylist.to/) [easy privacy list](https://easylist.to/easylist/easyprivacy.txt). This list will block all requests containing `?type=performance&` in them. This is used in many requests for graph information in Plan. 
### I would like to be able to...

View the graphs without having to disable Adblock. 

I'm not sure if a feature request is the right format to do this, but it is definitely not a bug.

**Comment by Rsl1122** [comment]
Due to the large amount of adblocking lists and software it is simply infiesible to test the website with them all. The parameters are required in the requests for Plan to know what kind of data to send back. 

I don't want to change names of these parameters for the sole reason of being unblocked by adblock, as that is likely what the actual ad sources are doing to their urls - It is an endless cycle with no winners. I changed `type=ping` to `type=aggregatePing` during interface redesign to do this, but it is now blocked anyway.

----

Most adblockers allow disabling the adblocker per website. Plan does not contain any ads, so the blocker can be disabled on the website without getting ads blasted to your face.

**Comment by evanmn** [comment]
You're right, I can see that this would be a frustrating endless cycle. I will close the issue.
