### ISSUE TITLE
Toggle User Registration

### ISSUE THREAD

**Issue by EnderGamingFilms** [plan-player-analytics/Plan#1446]
### Is your feature request related to a problem? Please describe.
No this is not related to a problem

### I would like to be able to...
I would like to just have a true/false in the config file that just enables or disables user registration from the website (So people can only register using the command in-game [for ops, etc...]). I use statistics on my server for Partners and High-Staff only, so having a way disable manual registrations would be cool.

**Comment by Rsl1122** [comment]
The register page requires the user to run an in-game command in order to register.
The page allows using the register command without the password ending up in the logs.

The user sees this after filling the registration form:
![kuva](https://user-images.githubusercontent.com/24460436/81780175-c40cd200-94fe-11ea-89b0-ad8d24f54c84.png)

This way you can still set the permissions in game to prevent the users from accessing certain pages.
While the permission situation right now is what it is, I'm currently working on improving that part of the plugin.

**Comment by EnderGamingFilms** [comment]
Alright cool, does this fill up storage if the player just spams the registration forum or is the data cleared if the user does not run the command, like a timeout?

**Comment by Rsl1122** [comment]
I guess I should make the registration details expire after a while.. The code, username and password are in memory until restart or the registration
