### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by ShadowChi1d** [plan-player-analytics/Plan#1474]
I think MongoDB support would be a great addition for those of us who have larger servers. As I’m sure you’re aware mongo provides much faster and more efficient storage

**Comment by Rsl1122** [comment]
Thanks for the suggestion, but this will not be implemented.

IMO MongoDB is not really a viable storage solution as it does not provide ACID quaranteed storage. Any transactions can go missing at any time. The speed they boast is because they do not write things on disk when something is stored so if anything happens between the transaction and hitting the disk then the data is forever lost.

In addition a lot of the queries in Plan rely on relational databases, and as MongoDB is a document database it does not provide an efficient way to join two pieces of data together (I've heard that doing this means rolling your own relational database-logic on top of mongo).
What mongo is good for is for storing large amounts of unimportant data, such as sensor data *when it is ok for the data to be lost* (Even then I'd consider PostgreSQL JSON fields to be more reliable).

I hope that clears up why I don't feel like Mongo is a good fit for Plan.
