### ISSUE TITLE
%plan_sessions_unique_players_day% Is wrong

### ISSUE THREAD

**Issue by lukeeexd** [plan-player-analytics/Plan#1480]
### Describe the issue

%plan_sessions_unique_players_day% shows inaccurate value
![1](https://i.tws.gg/GnMaipy5AI.png)
![2](https://i.tws.gg/yt1ZnhCARa.png)

### Server Information
**Plan Version:** 5.1 build 574
**Server:** Tuinity 1.15.2-R0.1-SNAPSHOT (git-Tuinity-"d8b8905" (MC: 1.15.2))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 5.4.34-1-pve
**Java Version:** 14.0.1, AdoptOpenJDK
**Java VM Version:** OpenJDK 64-Bit Server VM version 14.0.1+7, AdoptOpenJDK
Benchmarks
567 ms     -280 MB Enable
28 ms      -12 MB  subsystem-enable

**Comment by Rsl1122** [comment]
It looks like the placeholder displays value for last 24 hours (Same as Online Activity > Overview > Online activity as Numbers)
![kuva](https://user-images.githubusercontent.com/24460436/83964863-57e07c80-a8b8-11ea-9bcd-97459824dc98.png)
while calendar shows unique players since the start of today.

I have added following line to documentation to reduce the confusion

> All placeholders with `_day`, `_week` and `_month` show data for last 24h, 7d and 30d respectively.

I also added `%plan_sessions_unique_players_today%` that should have the same value as the calendar.
