### ISSUE TITLE
Question: Primary tab

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1512]
I would like the option to make TPS (for example) the "home" tab on the Performance page, instead of ALL. Is that supported? Without custom processing?

**Comment by Rsl1122** [comment]
This is possible with [Html Customization](https://github.com/plan-player-analytics/Plan/wiki/Html-Customization), I dunno  what you mean with custom processing - I am assuming it is something else here.

### Option 1

[the performance tab nav-link href](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/server.html#L106) can be changed to `#tab-performance&tps` & Plan will handle the required javascript call to Bootstrap

### Option 2

both
- https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/server.html#L946
- https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/server.html#L982
need to be modified. (Move `active` and `show active` classes to a different tab)

I would like to prevent situation where config options add javascript calls to the page, because that can get messy real fast.

**Comment by SlimeDog** [comment]
I was hoping to avoid HTML customization. As you may recall, early on I used it heavily, but with Plan 5.0 I rolled back to using mostly defaults. Today, I have only two custom JS files. But I appreciate the ease with which Plan supports customization, and will take that route.
