### ISSUE TITLE
Sessions: Calender to click a day to see who logged on when in that day.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#1531]
For session data, I would like to be able to click a day and have it show who logged on when for that day.
I need to go back a few days and find out who was online at an exact time to figure out if the server crash wiped these players data.

**Comment by Rsl1122** [comment]
This seems like a good addition, I'll have to see if it is possible to do.

Note that the feature probably won't arrive in time to figure out your current situation, so you might need to do so via alternative means.

**Comment by AuroraLS3** [comment]
Refining this ticket - The query page seems to have fulfilled the use-case with the *Played Between* -filter.

----

I think it might still be beneficial to see some kind of plot of who was online, but *the exact times* in the plot are a bit challenging.
As an example for plots of this type,
dumbell plot:
![image](https://user-images.githubusercontent.com/24460436/127037198-50e0f569-1df8-4424-a043-501f9be798ff.png)
x-range plot:
![image](https://user-images.githubusercontent.com/24460436/127037233-e6f26f1a-7d8f-49c9-9944-f73310001836.png)

Both grow vertically very rapidly as more and more players join. If a server gets 50+ unique players a day the plot quickly becomes difficult to read.

What might work is the calendar day view similar to that already on the player page, but in this case it would also list the player names.
![image](https://user-images.githubusercontent.com/24460436/127037557-bf88aced-8abb-4ecb-b825-84c690ed0fe6.png)

----

### TODO

- Figure out if it is possible to add to existing FullCalendar dataset dynamically, to load the day's sessions when clicked on.
- Add an endpoint for sessions that takes `server`, `before` and `after` as parameters, or modify the existing sessions endpoint to accept those as optional parameters. - use ISO-8601 to transmit dates only (no time) and apply config timezone in the query for the sessions.
- Write an event listener for FullCalendar day click
- Load data from that endpoint when a day on the calendar is clicked and add it to the calendar
- If it is not possible to add data on the fly, load the sessions for last 30 days into the calendar by default.

This has potential for timezone issues (#1239) since time is passed through: javascript -> endpoint -> code to apply timezone -> sql -> data render methods that format the time to ISO-8601 from milliseconds again so great care needs to be taken.

**Comment by AuroraLS3** [comment]
I think I managed to create a pretty elegant solution combining existing features.

Basically the calendar library supported clicking/dragging on the calendar to select dates. This lets user programmatically select two dates they would like to see data about.

Feeding the start and end date to the Query endpoint, using View and Played Between as the start and end date allowed dynamic querying of all players who played on those specific days, and then getting data about them.

This fulfills the needs of this ticket and more.

Example gif:
![calendar-demo](https://github.com/plan-player-analytics/Plan/assets/24460436/7396cb6c-1ce6-442e-9d9a-518cd0436fbe)
