### ISSUE TITLE
Crystal PVP as player kills

### ISSUE THREAD

**Issue by CM8DoubleCheck** [plan-player-analytics/Plan#1571]
Hi, 

I'm opening a semi-unique form of PVP server where crystals are used as the main meta. I was hoping to use plans PVP logging to create things like leaderboards and such, but I realized that when a player kills another player using an end crystal, it's not logged as a kill. I know this is unconventional and I believe Minecraft itself doesn't recognize this as a PVP method, but it would be extremely helpful at least to me if it were recognized in Plan.

Thanks,
DoubleCheck

**Comment by Rsl1122** [comment]
Conversation from discord

> DoubleCheck Today at 2:01 AM
Are end crystals (PVP) considered as PVP deaths/kills? I don't see it added as a kill on the dashboard or through the API. I'm working on a Crystal PVP server and would love to have them counted for leaderboards and stuff
Yeah, I only see actual weapon kills counted unfortunately

> Rsl1122 Today at 9:20 AM
Crystal beam is probably not in the handled entities (I didn't know player's could own crystal entities) - If you would like please open a PR that handles the beam kill
https://github.com/plan-player-analytics/Plan/blob/master/Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/listeners/bukkit/DeathEventListener.java#L88 You can likely see the handleProjectileKill method if you need an example (projectileName could be crystal beam)

> DoubleCheck Today at 9:25 AM
Well, it wouldn't be the beam kill itself. There's a PVP meta that uses Crystals as the main weapon where the explosion from them kills the opponent. It's not a recognized PVP method in the game itself so that is why plan doesn't pick it up. With Death Messages Prime and their addon for crystal PVP kills, it does log proper deaths with killer and a victim, but it doesn't seem to pass that on as an actual PVP death. Plan records the death, just not the kill. I'll open up a github request for this and hopefully it wouldn't be hard to implement

> Rsl1122 Today at 9:26 AM
Interesting
Sounds like a chain, hopefully spigot allows getting that chain without storing stuff after events
(eg. Player died -> get cause: Explosion -> get cause: Crystal -> get cause: Player hit the crystal)

> DoubleCheck Today at 7:21 PM
Yeah, there are a few plugins that recognize kills from end crystals, it would just be super nice if Plan could as well. --

----

There is no ETA for this feature due to the large feature backlog.
I'd estimate it to arrive within 1 month to 3 years.

If this feature is critical consider implementing it and posting a Pull Request. 

Here is some stuff to get started:

- <https://github.com/plan-player-analytics/Plan/wiki/Project-Setup>
- See the link in the conversation for a starting point (DeathEventListener)

**Comment by CM8DoubleCheck** [comment]
So as a workaround, I stumbled across this addon for DeathMessagesPrime - https://www.spigotmc.org/resources/dmpmonitorcompat.67404/

Quoting the section on what it does:
"
This add-on is designed for DeathMessagesPrime and some (chiefly chat) plugins that check the death message from PlayerDeathEvent using the MONITOR priority. While an accepted (and recommended) practice, any plugins using this approach will not be compatible with DeathMessagesPrime by default for technical reasons.

This plugin effectively creates a mock PlayerDeathEvent that will be sent to the PlayerDeathEvent listeners of the configured plugins. The mock event will have the correct player, drop, old XP and death message data, but all new XP data will be set to -1 (this way it is possible to tell the real and mock events apart)." 

I've tried adding "Plan" to the list of plugins to send the mock PlayerDeathEvent to, but it doesn't seem to do anything. Perhaps this has to do with priorities?

**Comment by Rsl1122** [comment]
> I've tried adding "Plan" to the list of plugins to send the mock PlayerDeathEvent to, but it doesn't seem to do anything. Perhaps this has to do with priorities?

Plan uses MONITOR priority like it wants, so it is not unfortunately because of the priority.

What is likely happening is that the death event is fired and Plan registers it as a death as normal - but Plan does not have any code that handles the entity that killed the player

```java
EntityDamageEvent entityDamageEvent = dead.getLastDamageCause();
if (!(entityDamageEvent instanceof EntityDamageByEntityEvent)) {
    return;
}

EntityDamageByEntityEvent entityDamageByEntityEvent = (EntityDamageByEntityEvent) entityDamageEvent;
Entity killerEntity = entityDamageByEntityEvent.getDamager(); // This one
```

The killer entity is likely an ender crystal or explosion - neither of which have code in Plan to be handled as a player kill.

**Comment by unnamedlife** [comment]
Sorry I might sound dumb since I just stumbled across this, but has anyone figured how to track endcrystal kills and put that on a leaderboard? Thank you (I own a crystal pvp server)

**Comment by AuroraLS3** [comment]
@unnamedlife You need to look for the killer of player, and if it's an EnderCrystal find the killer of the EnderCrystal
https://github.com/plan-player-analytics/Plan/commit/89a3d63d8b0166803227e68de3c398e77c50a5d8

**Comment by unnamedlife** [comment]
> 

I'm working on a server and I need a tracker of end crystal kills, you seem to know alot! is it possible I can pay you for a plugin that does this?

**Comment by unnamedlife** [comment]
> There are some chains of actions that this code doesn't track like if the endcrystal is killed by a projectile coming from a dispenser (Who triggered the redstone?) or if it's killed by an explosion chain (who triggered the first explosion?)

Oh okay I didn't realize the plugin tracked end_crystal kills !, I will be adding it to my server, but how can I now use this statistics and put that on a leaderboard? I know placeholderapi tracks kills with statistic_player_kills, so for e.g how can I use the end crystal tracker to make a leaderboard with end crystal kills?

**Comment by AuroraLS3** [comment]
There isn't a kill based placeholder like that, but feel free to make a suggestion.

Another alternative is to use the Query API (see wiki) to implement another plugin that looks up kills from plan_kills table where weapon is 'End Crystal'
