### ISSUE TITLE
Source of Money & Balance sheet

### ISSUE THREAD

**Issue by Anacraft** [plan-player-analytics/Plan#1631]
If I understood correctly, this project allows you to improve your skills in statistics. 

If I may, I have an idea to suggest to you. It would be very interesting to have analyzes on the economy of the server. 
In particular on the scale of a player knowing how much he won during the day how much he spent. 
Know which plugins the money comes from (jobs, quest, shop, crates). 
These analyzes will make it possible to better balance the economy and to detect usebugs. 
This will allow to know the economic model of the server.

Thanks for reading, have a nice day

**Comment by AuroraLS3** [comment]
After looking into it, I unfortunately found that there is very limited APIs for figuring out where the money is coming from (Vault doesn't even have events for economy) so this is unfortunately out of scope.

**Comment by Kopo942** [comment]
Just throwing ideas around, but would it be too much of a hassle to use the APIs of the most popular economy-implementing plugins to see where the money is coming from and where it is going? Most major plugins have good enough APIs that they fire events whenever they're doing a transaction etc, so hooking to those would provide us with the information. Of course, plugins without the events would be out of scope. 

I've been thinking about making a plugin like this for long, and it would be a great extension to Plan's statistics also.

**Comment by AuroraLS3** [comment]
Having a good API and being a popular plugin don't necessarily go hand-in-hand, and since there are probably thousands of plugins that use economy, eventually people would be suggesting more obscure and less well built plugins.

Relying on 3rd party code (especially plugins) has its own problems; some code is proprietary, most don't have the necessary documentation, APIs can break on a whim, even the maven repositories hosting a 3rd party dependency can go down all of a sudden. Some artifacts don't host a maven repository, some don't even support jitpack.

Doing this alone is doing maintenance forever, or otherwise the plugin would produce crap data.

If it gained popularity like that of PlaceholderAPI and other developers were keen on implementing support for the source - sure.  but I don't see that happening with an api that doesn't directly appear inside the game to the end-user.
