### ISSUE TITLE
Feature request: Block statistics

### ISSUE THREAD

**Issue by DaniGTA** [plan-player-analytics/Plan#1642]
I have a minecraft server where only building is done, meaning the statistics for deaths and kills are not relevant but what would be relevant is the number of blocks placed & blocks destroyed.

It would be nice to see how many block's a player has placed or destroyed.

**Comment by Rsl1122** [comment]
This issue is a low priority feature because this data is a statistic - which means it either takes a lot of space (per session? per block type? per world? per server? per player?) or doesn't convey useful information (does it say something if player A has placed 1304315314 blocks and broken five less)

What kind of information would you want to figure out from this data?

**Comment by DaniGTA** [comment]
This statistic would rather be addressed to the players than to the server owner.

For me the block statistic is like killed mobs, doesn't say much for the server owner but the players can compare themselves with it.

The server owner can use the block statistics to see the **building activities** on the server.

Which block is destroyed might only be relevant for ore's, the remaining blocks can be counted as one number **per session**.

**Comment by wysohn** [comment]
I also support this.

In server owner's perspective, providing block statistics per its type would be super useful, especially in survival server.

It may can be used to draw distribution of number of blocks mined in certain period, or maybe just in total would be also useful to decide how much resources are being produced in the server.

**Comment by AuroraLS3** [comment]
Considering this resolved with added Logblock support
