### ISSUE TITLE
New placeholder for player session stats

### ISSUE THREAD

**Issue by wysohn** [plan-player-analytics/Plan#1663]
### I would like to be able to..
Currently, we can check the player's 'regularity' based on their time being online, etc. I don't really know how it is calculated, yet I know that we can check it.

Is it possible to make a placeholder to get the information directly?

I've tried to use the Query API, yet I can't really find the field that exactly gives the information I want.

I think the calculation is done internally, and if it is so, at least let me know where the calculation logic is.

I've been searching for the Wiki, but I couldn't find anything similar to what I want.

Many thanks!

**Comment by Rsl1122** [comment]
Here is how the activity index is calculated, and how different activity groups relate to it
https://github.com/plan-player-analytics/Plan/wiki/Migration-guide-from-Version-4.x.x-to-Version-5.0#changed-activity-index-formula

Here are where the index is calculated in sql
- for server https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/analysis/ActivityIndexQueries.java
- for network https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/analysis/NetworkActivityIndexQueries.java

Also the same calculation in Java code in case that is easier to understand (it is certainly easier to read)
- https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/mutators/ActivityIndex.java#L116

----

### Features to be implemented for this request

- Query for the index could be added to CommonQueries since it is such a complex query to write on your own (or copy).
- Placeholder for the activity index value
- Placeholder for the activity group
