### ISSUE TITLE
[object Object] showing in Online Activity > Sessions > Recent Sessions > Kill history

### ISSUE THREAD

**Issue by helpimnotdrowning** [plan-player-analytics/Plan#1675]
### Describe the issue

Clicking on a session for kill details shows PlayerName > [object Object]
![image](https://user-images.githubusercontent.com/35247379/102643234-920ebe80-4124-11eb-8ee0-052abfb901c4.png)
![image](https://user-images.githubusercontent.com/35247379/102644771-fb8fcc80-4126-11eb-9503-7249de79fdb2.png)
![image](https://user-images.githubusercontent.com/35247379/102644802-077b8e80-4127-11eb-994f-ad107bb0f434.png)

### Server information

**MC** : 1.16.4
**SERVER** : Paper 1.16.4 build 323
**PLAN** : 5.1 build 813
**OS** : Windows 10 20H2
**JAVA** : AdoptOpenJDK JDK 11.0.9+11 Hotspot
**DB** : SQLite

### Exceptions & Other Logs

No logs or errors in console

### Additional information

[object Object] doesn't show up when looking at a players PvP & PvE stats
![image](https://user-images.githubusercontent.com/35247379/102645118-938db600-4127-11eb-98fb-5d2e08d25f0b.png)

**Comment by Rsl1122** [comment]
Ah I see.

This is caused by the victim name being an optional property of `PlayerKill`, so when before it was `String` or `null` now it is `Optional<String>` which javascript then sees as a javascript object, which is printed as `[object Object]`

Line with the issue <https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/mutators/SessionsMutator.java#L291>
(Coding mistake, should have `Optional#orElse` call to turn it to String)
