### ISSUE TITLE
Nucleus tab on server inconsistent

### ISSUE THREAD

**Issue by carbotaniuman** [plan-player-analytics/Plan#1688]
### Describe the issue

Nucleus tab on the main website provides weird (inconsistent/missing data)
![image](https://user-images.githubusercontent.com/41451839/104403284-d6239200-551d-11eb-82b9-e9ff1095dad1.png)

### Server information

Plan Version 5.1 build 813
Spongeforge 1.12.2-2838-7.3.0

### Exceptions & Other Logs

N/A

### Additional information

I may be misunderstanding this tab, but the punishments tab doesn't update (the one linked to the player does though), and the stuff in there such as kits and homes only updates on restart.

**Comment by Rsl1122** [comment]
> I may be misunderstanding this tab, but the punishments tab doesn't update

Hmm, it appears that the punishment tab for some reason has a table that is not specified in the code (and that's why it doesn't update).

> the stuff in there such as kits and homes only updates on restart.

Nucleus Extension is set to only update this data when Plan enables. (default)

Here is a snippet from the documentation in case that clears things up
![image](https://user-images.githubusercontent.com/24460436/104417423-01d66480-557e-11eb-8df8-117797e39b6b.png)

**Comment by carbotaniuman** [comment]
Ah ok. Also you said it only updates when Plan starts but the linked screenshot also says when players join and leave? I looked at the extension and it doesn't seem to override that method.

**Comment by Rsl1122** [comment]
Yep and yep.
The player join and leave usually only affects the data on the player pages (and totals and averages of them on the server page).
The linked extension has the default behavior.
