### ISSUE TITLE
DATABASE

### ISSUE THREAD

**Issue by HiJackerRZ** [plan-player-analytics/Plan#1727]
### Is your feature request related to a problem? Please describe.

Can you please add support for MONGODB becouse mysql is not so good and is crashing my dedicated server!
### I would like to be able to..

I want to can be able to use this plugin whit mongodb!
Thank you!

**Comment by Rsl1122** [comment]
Mongodb is not a viable database for Plan due to the analytical queries that rely on relational databases. Using mongo would reverse the memory usage reductions made in 5.0, moving all analysis to memory and that was not a good approach.

See #1474 for additional reasons why mongodb won't be implemented as a database for Plan.
