### ISSUE TITLE
Rewrite locale replacement for the web pages

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1733]
### Is your feature request related to a problem? Please describe.

Current locale functions by find-and-replace on the files. Issues arise due to javascript containing some of the same words.

- This is a very haphazard and fragile implementation that has lead to a lot of issues where the page doesn't load (#1373, #1372, #1334, #706)
- Some non-translated things are translated as well #1092, which makes the order in which things are replaced (placeholders first or locale first?) difficult as well. Currently the locale is applied last to avoid placeholders breaking in a similar way as javascript.
- Care needs to be taken when writing new javascript and adding new locale lines to not match existing replace rules or code (Cumbersome)

This is due to technical debt taken on when redesigning the locale system last time: https://www.spigotmc.org/threads/how-to-replace-text-in-part-of-a-string-but-leave-other-part-untouched.394423/#post-3566310

> Existing solution was in place that replaces default text with replacements if they are overridden, and the text to translate was already hardcoded in the files (case 2).
> So solving this was less effort overall. 

Removing this technical debt would improve stability of updates and increase confidence in writing javascript code and locales without resorting to extra characters in the translation strings just to not replace words in the code.

### I would like to be able to..

- Not use find-and-replace for translation

Suggested alternatives:

- Additional XMLHTTPRequest for locale data, javascript replaces language on the page according to the data (https://www.spigotmc.org/threads/how-to-replace-text-in-part-of-a-string-but-leave-other-part-untouched.394423/#post-3566266)

**Comment by Kopo942** [comment]
I was thinking about writing an in-house library for this, but stumbled upon [i18next](https://www.i18next.com/) which to me looks very promising. The library has been around since late 2011 and to this date receives regular updates. The sheer amount of supported frameworks, backends and plugins (and the lack of jQuery!!) makes this a very compelling option. 

For our use case, this library has support for [JSON backends](https://www.i18next.com/overview/plugins-and-utils#backends), [HTML data attribute-based](https://github.com/mthh/loc-i18next) (and JS-based) translations, [caching](https://www.i18next.com/how-to/caching), [language detection](https://github.com/i18next/i18next-browser-languageDetector) and [context](https://www.i18next.com/translation-function/context) & [interpolation](https://www.i18next.com/translation-function/interpolation), so basically everything we need.

If you think this looks like a good candidate, I'd be more than willing to help integrate this into Plan.

**Comment by AuroraLS3** [comment]
Sounds good

**Comment by AuroraLS3** [comment]
### TODO

- Write a yml locale file writer and reader that uses Config (No need for configurate yet)
- Add `getKey()` method to `Lang` interface for figuring out yml paths for translations
  - Add yml keys to the different enums
- Write something that takes `Locale` and outputs json i18n-next can use
- Add `Resolver`s for the locale json
- Add i18n-next library to the frontend
- Write a function that requests the locale json
- Wire up i18n-next so that it replaces language on the page (This is probably the part that takes longest)
  - Add language keys to the html and javascript files where necessary
  - If any current translations need modifications (for example removing html tags and such), write a LocaleUpdater similar to `ConfigUpdater` that allows writing these patches to all locale files.

**Comment by Kopo942** [comment]
>Add getKey() method to Lang interface for figuring out yml paths for translations
> - Add yml keys to the different enums

Done, yml keys are still blank.

**Comment by Kopo942** [comment]
Todo fix: LocaleJSONResolver requires auth even though it is an instance of `NoAuthResolver`
