### ISSUE TITLE
Write customizable web files for Plan on enable

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1745]
### Is your feature request related to a problem? Please describe.

Currently html customization requires a visit to the website. It would be a lot easier if it didn't need that. I dunno if it's possible to go through the directories in the jar to not define the files manually.

Alternatively an enum could be used for all these files since some files are already defined for export, so one place to add files instead of 5 would be good in the code.

----

### TODO

- Add a task that runs on enable which asks `ResourceService` for each of the enabled customized resources in the config
  - The config keys have `.` replaced with `,` which is easy to reverse
  - Config keys can be easily traversed with ConfigNode

**Comment by wereii** [comment]
One solution for this (and #1846 ) could be to split off the static content (website) and only expose the Json API on the plugin.

This would allow the ability to quickly edit the website content but also create a place for specialized webservers (eg, nginx, apache) to plug itself in with it's full set of abilities (nginx: rate-limits, caching, ip access, SSL, basic auth...)

This idea comes from the UNIX's "do just one thing and do that well", so instead of Plan trying to be both full fledged webserver **and** Minecraft server analysis panel, it could try to do _primarily_ just the latter. Which, I guess could also save some of the precious JVM cpu cycles of our minecraft servers.

**On the other hand..**
I can see this breaking the plug n' play way of just dropping `.jar` into plugins and analyzing away, though if you use routing, it could be made configurable if Plan should or shouldn't serve the full site (both static content and API, or just API).
In both cases it would be nice to drop the website into some `plugins/Plan/website/` and when Plan is also serving the website, just enable the `/ => Plan/website/` webserver route.

Just my few cents. Thanks for making Plan, works well and looks awesome:)

**Comment by AuroraLS3** [comment]
Big thing with using specialized webservers is that a lot of hosted servers don't have them available. It is a lot less asked of a hosting provider to have a free port than to have nginx/apache instance per server (sure there are those, but it is not the common approach, especially on shared hosting).

Less installation to do as well, like you said, **plug 'n' play** - It's rather important and a lot of effort goes into it staying that way:
- Single jar for all platforms is done for the same reason
- Updates automatically modify databases and configs to new versions
- Installation hassle related tickets have been prioritized in the past, as it creates more work for assisting with those installation issues. Less assisting to do, the more time and energy is available for meaningful stuff
- Wiki is updated usually when users get stuck on something during installation

With a webserver on the plugin the features of specialized webservers are also available to those who have them via reverse-proxying.

----

Rate-limiting would still be an issue exposing just the json API - that json API needs a webserver anyway, so why not host the static content too - static content barely adds cpu overhead, other than occassional GC. Some of the static content is also less static as it might initially seem, since different json API calls might need to be made for different servers/players. Ensuring that a static website can handle that is a challenge itself (of course doable).

Adding any feature flags also increases complexity and I want to avoid increasing complexity at this point.

----

I get what you're going for with the "do one thing well" split, the possibility to do the analysis (most cpu intensive stuff) off the minecraft server.

The problem domain based split for Plan would be *data-gathering* vs *visualization*. For now they are too intertwined in the project to be split into separate modules, which is why a standalone mode doesn't exist either.

This split is the same that is found in competing plugins, but there the visualization part is usually done on someone else's machine while the plugin only performs data-gathering. Main benefit of doing the visualization on the server machine is that the analysis doesn't need to scale as heavily (it's non-centralized between different servers), and so analysis can be more in-depth or computationally intensive than would be possible on a centralized system. Main limitation of the scalability of centralized analysis is the money available for scaling computation after all.

**Comment by wereii** [comment]
I see that Plan's (or of server plugin with web frontend) requirements are way more broad then I imagined, I am coming from self-hosted environment so, that was a miss from me.

**Comment by rymiel** [comment]
Should this feature invalidate the ❗**bold warning** on the wiki at https://github.com/plan-player-analytics/Plan/wiki/Html-Customization

**Comment by AuroraLS3** [comment]
Yes, I'll have to do that when the release is out
