### ISSUE TITLE
Huge performance concerns with the current unoptimized mcMMO implementation in Plan

### ISSUE THREAD

**Issue by nossr50** [plan-player-analytics/Plan#1791]
**Performance Issue when using Plan with mcMMO**
Plan will grab data for all players on a server (both online & offline) from mcMMO very frequently, one player can cause Plan to send countless requests to mcMMO for their data per second, this is scaled up dramatically for servers with a lot of players and or server that have been running for a long time with a lot of database entries (which potentially have 10,000+ players to grab data for).

**Why this is a problem:**
Normally this would not be a problem if the player was online as mcMMO caches that data, but the issue arises when the player is offline as mcMMO loads their data up fresh from the DB every time, a lot of resources are created and thrown away in this process.

**Potential Solution:**
I would suggest that Plan grab and cache PlayerProfile objects for offline players and update/discard them as needed as the current implementation for the mcMMO extension in Plan does not account for the expensive operations in grabbing offline player data with mcMMO API calls.

This issue came to my attention as I was fixing some console spam when Plan and mcMMO are used together (which is now fixed)

**Comment by AuroraLS3** [comment]
Thank you for bringing this to my attention.

Currently most of the methods are fired when player joins (priority MONITOR) or leaves (priority NORMAL). If there appear to be a lot of calls for offline players then the leave is the most likely culprit.

I don't know how many players are fetched into memory when the leaderboard is calculated, as that is another potential read-hog. - it was assumed that this method has its own optimizations behind it due to the pagination
```
for each skill:
    mcMMO.getDatabaseManager().readLeaderboard(skill, 1, 3);
```

I'll consider removing these calls in the next version to reduce the impact.
