### ISSUE TITLE
[Feature Request] Limit Registration to permisisons/Disable Regestration

### ISSUE THREAD

**Issue by Myzumi** [plan-player-analytics/Plan#1797]
### Is your feature request related to a problem? Please describe.
This feature is not related to a problem

### I would like to be able to..
Add a config option to only allow staff members to create a account and removing the "Register Account" option on the webpage to make plans ony accessable for staff members

**Comment by AuroraLS3** [comment]
Registering is limited with the `plan.register.self` permission (Registration needs to be finished in-game or on console)
https://github.com/plan-player-analytics/Plan/wiki/Commands-%26-Permissions

Removing the button from the page is currently not possible because the access controls are primitive (Would need feature https://github.com/plan-player-analytics/Plan/issues/1623)

**Comment by AuroraLS3** [comment]
On a further thought I realized that removing the button is not possible even with that feature, because people are not logged in when registering (There is no way to know who is staff when viewing the login page)

If you want to remove the button completely customize login.html with https://github.com/plan-player-analytics/Plan/wiki/Html-Customization
