### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by DrexHD** [plan-player-analytics/Plan#1956]
I would like to see support for the modding platform [fabric](https://fabricmc.net/). 

To accomplish this I would suggest either implementing a Plan API fabric mod that implements any events that aren't provided by [Fabric API](https://github.com/FabricMC/fabric) or just adding the events to the main project, with the risk of them breaking throughout major versions.

**Events provided by Fabric API:**
- [Death](https://github.com/FabricMC/fabric/blob/1.17/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java)
- [World Change](https://github.com/FabricMC/fabric/blob/1.17/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerEntityWorldChangeEvents.java)
- [Player join](https://github.com/FabricMC/fabric/blob/1.17/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayConnectionEvents.java#L46)
- [Player leave](https://github.com/FabricMC/fabric/blob/1.17/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayConnectionEvents.java#L57)
- [Player login](https://github.com/FabricMC/fabric/blob/1.17/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayConnectionEvents.java#L31)

**Mixin injection points for other events**

GameMode change (ServerPlayerEntityMixin)
```java
@Inject(method = "changeGameMode", at = @At(value = "INVOKE", target = "Lnet/minecraft/server/network/ServerPlayNetworkHandler;sendPacket(Lnet/minecraft/network/Packet;)V"))
public void onGameModeChanged(GameMode gameMode, CallbackInfoReturnable<Boolean> cir) {}
```
Chat (ServerPlayNetworkHandlerMixin)
```java
@Inject(method = "onGameMessage", at = @At(value = "HEAD"))
  public void onChatMessage(ChatMessageC2SPacket packet, CallbackInfo ci) {
    if (!packet.getChatMessage().startsWith("/")) {}
  }
```
Player move (ServerPlayNetworkHandlerMixin)
_This would get run every time a player sends a move packet, we could also inject at a later point to let minecraft handle it's move validation checks_
```java
@Inject(method = "onPlayerMove", at = @At(value = "HEAD"))
public void onPlayerMove(PlayerMoveC2SPacket packet, CallbackInfo ci) {}
```

**Comment by DrexHD** [comment]
I was able to find events for login, join and leave in [fabric-networking-api-v1](https://github.com/FabricMC/fabric/tree/1.17/fabric-networking-api-v1) leaving just three events unimplemented.

**Comment by xXxIshadowxXX** [comment]
> I was able to find events for login, join and leave in [fabric-networking-api-v1](https://github.com/FabricMC/fabric/tree/1.17/fabric-networking-api-v1) leaving just three events unimplemented.

that's interesting, i have a fabric server myself so I'm very interested in having plan word for fabric servers

**Comment by AuroraLS3** [comment]
### TODO

- Add a new gradle module for fabric
- Add fabric as a dependency for the module
- Add module to be shaded in to the plugin module so that it ends up in the final jar
- Write fabric support for https://github.com/plan-player-analytics/Platform-abstraction-layer - this can be implemented in the fabric module and later moved to PAL if necessary.
  - Implement command logic using brigadier
  - Implement task scheduling using ScheduledExecutorService
  - Implement console logging for fabric
- Write a plugin class that initializes a fabric specific dagger component and initializes PlanSystem.
- Write data collection logic for the events (Likely very same as other server platforms)
  - It is okay if some data is not supported like: Join addresses, geolocation (if IP access is difficult), ban status, operator status, nicknames - Main thing to get working is sessions and world playtime.
- Write data collection logic for graph data
  - a timed task that gathers performance metrics
  - the same task should gather online player count (*Unknown yet how to do this*)
  - It is okay if ping data is not supported.
  - It is okay if TPS data is not supported if fabric doesn't have a ready made api for that, or can not schedule tasks on the server thread.
- Write some logic for visualization that shows "Unavailable" when that specific data is not available on the platform.

**Comment by DrexHD** [comment]
> It is okay if some data is not supported like: Join addresses, geolocation (if IP access is difficult), ban status, operator status, nicknames - Main thing to get working is sessions and world playtime.

The [Fabric Join Event](https://github.com/FabricMC/fabric/blob/12865e786ce2102d344304a679b70084be84d166/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayConnectionEvents.java#L73) provides the `ServerLoginNetworkHandler`, which contains the  `ClientConnection`, which contains the `SocketAddress` for easy IP access.
Ban status can be achieved using `BannedPlayerList` (needs GameProfile) and `BannedIpList` (needs IP), which is accessible through the MinecraftServer instance (acquired on [Server Start](BannedIpList)). Operator status can be checked through `PlayerManager` using the players GameProfile

For sessions, we could just store the time on Join

> It is okay if ping data is not supported.

Ping is stored and updated in the `ServerPlayerEntity` class in ms.

> It is okay if TPS data is not supported if fabric doesn't have a ready made api for that, or can not schedule tasks on the server thread.

TPS isn't natively found anywhere, but using the long[] (in `MinecraftServer`) of the last 100 tick lengths and the [Tick Event](https://github.com/FabricMC/fabric/blob/12865e786ce2102d344304a679b70084be84d166/fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerTickEvents.java#L122) it should be calculatable relatively easy.
