### ISSUE TITLE
Apache proxy server suggestion

### ISSUE THREAD

**Issue by GoedendagMC** [plan-player-analytics/Plan#2081]
**https://github.com/plan-player-analytics/Plan/wiki/External-Webserver-use:-Reverse-proxy#apache-reverse-proxy**: 

### The code for a plan.example.com.vhost file inside '/etc/apache2/sites-available' should be:
```
<VirtualHost *:80>
  ServerName plan.example.com
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L] 
  ProxyPreserveHost On
  ProxyPass / http://0.0.0.0:8804/
  ProxyPassReverse / http://0.0.0.0:8804/
</VirtualHost>
<VirtualHost *:443>
  ServerName plan.example.com
  DocumentRoot "/var/www/plan.example.com"
  SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/plan.example.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/plan.example.com/privkey.pem
  ProxyPreserveHost On
  ProxyPass / http://0.0.0.0:8804/
  ProxyPassReverse / http://0.0.0.0:8804/
</VirtualHost>
``` 
### SSL for the site:
In this configuration, you should generate a certificate like this:

```
sudo apt update
sudo apt install -y certbot
sudo apt install -y python3-certbot-apache
certbot certonly --apache -d plan.example.com
```

### Enabling the website:
You have to manually create the '/var/www/plan.example.com' directory first (even though it won't be used at all, Apache won't start without it). To enable the website now, type:
```
sudo ln -s /etc/apache2/sites-available/plan.example.com.vhost /etc/apache2/sites-enabled/plan.example.com.vhost
sudo a2enmod rewrite proxy proxy_http
systemctl restart apache2
```
### Please note:
This install assumes a Ubuntu/Debian system. Please adjust the procedure accordingly to your Linux distribution.

Note that this puts Plan in the root of plan.example.com, if you want it in a subdirectory just change `/ http://0.0.0.0:8804/` to `/subdirectory http://0.0.0.0:8804/` in the .vhost file.
Make sure to replace 0.0.0.0:8804 with your server's ip and Plan port

If you get an error "ERR_TOO_MANY_REDIRECTS", remove line 3;4;5 "  RewriteEngine On;RewriteCond %{HTTPS} !=on;RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]". The site will then not automatically use HTTPS though, unless proxied through for example Cloudflare.

**Comment by AuroraLS3** [comment]
Nice one, thanks

**Comment by Kopo942** [comment]
Some notes:
- The `DocumentRoot` directive can simply be `/var/www/html`, since that is the default directory and exists almost always
- The flags for `RewriteRule` should be `[END,NE,R=permanent]`. A browser caches the permanent HTTPS redirect, saving an extra request for the redirect when accessing the site. `NE` disables hexcode conversion for special characters.
- The `<VirtualHost *:443></VirtualHost>` definition could be wrapped in a `<IfModule mod_ssl.c></IfModule>` condition to make sure the SSL module is enabled.
- Apache2 virtual host filenames are recommended to end in `.conf`, so I'd change this in the example. Thus, `sudo ln -s /etc/apache2/sites-available/plan.example.com.vhost /etc/apache2/sites-enabled/plan.example.com.conf` can be replaced with `sudo a2ensite plan.example.com`

**Comment by AuroraLS3** [comment]
Included to the wiki page.
