### ISSUE TITLE
Improve player-specific info page on mobile

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#2087]
Looking at a really active players statistics he's played for 23 days so far which is amazing.. and well, the display of the stats.. are a bit... Off putting
![Screenshot_20210918-165513.jpg](https://user-images.githubusercontent.com/70318494/133887210-787fedba-9a20-4339-b0a9-c736f41eedb8.jpg)

Registered and activity index has incorrect spacing..

At the top idk why the player head is displayed in between times kicked and player kills, it would be better if the player head was put in the top right of the box

And in the list players page, I can't see much info other than activity index and name. I am thinking a sideways scroll bar within the box to see other information can achieve this.

Plan-5.4-dev-build-1412

**Comment by AuroraLS3** [comment]
The head is between the stats since the page was designed desktop first, and when you look at the page on desktop the head has stats on both left and right side. Something is definitely up with the bottom side of that card. 

Tables are notoriously difficult to show on mobile, but I'll see what I can do..
