### ISSUE TITLE
ip

### ISSUE THREAD

**Issue by yellow-pillow** [plan-player-analytics/Plan#2106]
### I would like to be able to..

it would be nice to add an ip address to the player's information so that you can search for a person's twinkie accounts.

### Is your feature request related to a problem? Please describe.

it would be nice to add an ip address to the player's information so that you can search for a person's twinkie accounts.

**Comment by AuroraLS3** [comment]
Since IP addresses are classed as personal data under GDPR there needs to be a legal basis for collecting that data.

Because I don't want to consult a lawyer about this (and I don't want users of Plan to need to do that either), this data will not be added to Plan directly.

You can use other plugins that integrate with Plan, such as [egg82's AltFinder](https://www.spigotmc.org/resources/altfinder.57678/)
