### ISSUE TITLE
ReferenceError: updateGraphs is not defined

### ISSUE THREAD

**Issue by Shinigami92** [plan-player-analytics/Plan#2176]
### Describe the issue

When I visit the page I get a browser console error. From the side itself I don't see any errors but just sometimes slow initial loading graphs. But after around 1min or so, everything works fine.

### Exceptions & other logs

```text
ReferenceError: updateGraphs is not defined
    at changeHighChartsNightMode (color-selector.js:474)
    at color-selector.js:483
    at color-selector.js:496
changeHighChartsNightMode @ color-selector.js:478
```

### Plugin versions

https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1494

### Additional information

![image](https://user-images.githubusercontent.com/7195563/144207669-fdf26b26-3130-4c17-90e4-055a6c16d361.png)

<img src="https://user-images.githubusercontent.com/7195563/144207725-0cc839cc-c051-48fd-852d-38ecb4a91940.png" width="400px"/>

---

This plugin is really nice :+1: I love the player times and seeing the RAM + CPU usage together with player-count.
It's really great :heart:

**Comment by Shinigami92** [comment]
I found these related lines:

https://github.com/plan-player-analytics/Plan/blob/257c7bdb7ac0b721e2098005b9f575f4de5fbd04/Plan/common/src/main/resources/assets/plan/web/js/color-selector.js#L474

https://github.com/plan-player-analytics/Plan/blob/257c7bdb7ac0b721e2098005b9f575f4de5fbd04/Plan/common/src/main/resources/assets/plan/web/js/graphs.js#L811-L831

Maybe there is just an issue with that it calls it before it was defined or somewhat :thinking:

**Comment by Shinigami92** [comment]
Oh, I forgot to tell that I **don't** use the native cert version.
I use an nginx that serves the side with https over another port mapped to the local internal default port 8804.
Not sure if this is in any way related.

I don't use sub-pathes, it's just `<my-domain>:<my-port>` + basic_auth

**Comment by AuroraLS3** [comment]
The 1st error occurs on pages where there are no graphs and graphs.js is not loaded.
As you can see in the error catch block there is an error message related to Highcharts not being defined (it's the library used to draw the graphs) - I'm guessing that updating Highcharts somehow changed the error.
It can be safely ignored since it was caught and logged.

----

The 2nd error occurs on this line
https://github.com/plan-player-analytics/Plan/blob/113829477c06fff5a91bde45e1f4f2408dc0f047/Plan/common/src/main/resources/assets/plan/web/js/graphs.js#L832

Which would suggest that loading world pie data failed for some reason - I'm little uncertain why this would happen, but make sure you don't have html customized files or cloudflare cache messing things up with old versions of javascript files `graphs.js` or `server-values.js`.

There's going to be an update tomorrow which may fix this (I dunno if it does)

**Comment by AuroraLS3** [comment]
Has the issue been resolved?

**Comment by Shinigami92** [comment]
I think no :confused: 

![image](https://user-images.githubusercontent.com/7195563/146182871-35138c27-d6c0-44b2-8d8a-73d6ce4c258f.png)

But IMO `5.4 build 1516` runs more smoothly than version before. Not perfect, but much better :slightly_smiling_face:

**Comment by AuroraLS3** [comment]
Alright but the grapsh are now loading? 🤔

**Comment by Shinigami92** [comment]
Yes, they did almost also did before. It's just that sometimes it takes really long and/or you need to reload the page and then it works. So sometimes only for the first time it doesn't load successfully. Regardless of that, the error seems to show up always.

IMO it could be a problem of loading a script to late and then on second try it's cached or somewhat.

**Comment by AuroraLS3** [comment]
Alright the issue is probably actually #2196 - I'll leave this open since I see that the logs on the browser console could be cleaned up a bit
