### ISSUE TITLE
Live-view

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2234]
### I would like to be able to..

See a live-feed of a server when it is online.

Ideally this would be a separate tab on the website using a websocket to communicate.
I am unsure of the viability at this time.

### Is your feature request related to a problem? Please describe.

survey answer

- I am thinking about live statistics visualization. When the server is online, live graphs containing RAM, CPU, disk, mobs, chunks, players, tps, etc. could be available. I imagine it'd be resource intensive for some but its just an idea!

**Comment by Futodama** [comment]
It is easier to do not "in real time", but an update once a minute or even configurable. Constant updating of the information of such a complex plugin will greatly affect the performance of the server.

**Comment by AuroraLS3** [comment]
The intention is not to change existing behavior, but to add a new page to the plugin where live information can be seen in real time.

**Comment by Futodama** [comment]
But in any case, this will force the plugin to constantly poll the server continuously. In this case, it is necessary to limit the information on such a page to a certain set of data.

How do you like the option to display on such a page a list of players and data about them from plug-ins that constantly do surveys by themselves? An example of such a plugin: "Core Protect" and "Essentials", well, or make it so that the list of players is displayed there as on a regular page, but in a table with real-time information.

I don't think I'm meddling in my own business...

**Comment by AuroraLS3** [comment]
It's going to use a websocket to avoid needing to poll data - instead the server will push data to the page through websocket continuously as it becomes available.

For that reason it will be a limited set of data.
