### ISSUE TITLE
Playtime

### ISSUE THREAD

**Issue by JasperYTofficial** [plan-player-analytics/Plan#2240]
### I would like to be able to..

I am currently using https://spigotmc.org/resources/bungeeonlinetime.795/ to monitor the total playtime of a player on my Bungeecord network, and https://spigotmc.org/resources/playtime.26016/ to monitor the playtime per server.

Is it maybe possible to integrate these plugins with Plan? Or to import the data from these plugins into my Plan?
Now there is missing a lot of hours in the statistics from Plan which I think is very sad and kinds ruins the monitoring of my players playtime.

### Is your feature request related to a problem? Please describe.

-

**Comment by AuroraLS3** [comment]
The 1st plugin seems to have an API but the 2nd one does not.

I can try integrate this ticket to #872, but no promises. The intake for 3rd party plugin data is not yet finished (I'm currently testing the API I made with Plan internals to make sure it holds up).

Different sources may provide conflicting information.

To solve the conflict:
- On game servers take the highest playtime reported (and if Plan has been installed before the import occurs reduce any Plan recorded playtime from that value since we assume Plan records accurate playtime data after installation)
- On a proxy server take the time and reduce any other recorded playtime from and place the rest under "unknown"-source, and reduce the unknown source any time any further data is input.
  - If at any point the "unknown"-source gets to 0 then it can be assumed that the other data was more accurate.
