### ISSUE TITLE
Add network placeholders that show data from the whole network

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [plan-player-analytics/Plan#2267]
### I would like to be able to..

See top playtime placeholder values on the network level instead of server

### Is your feature request related to a problem? Please describe.

Both placeholders to be the same value.

As discussed in discord, I include the images as well, maybe it helps you more when u see the different values.
In short, the top values r different than the ones by the players personal ones which it shouldn't be.
total1:
https://prnt.sc/26ow6jz
monthly:
https://prnt.sc/26owbla
weekly:
https://prnt.sc/26owc88
daily:
https://prnt.sc/26owcxo
personal:
https://prnt.sc/26owd4s

**Comment by ILikeOrangeJuice** [comment]
Hey! :)

I saw you added new playtime placeholders in a fresh issue, so I thought I ask about this one here.
Is there any progress on this one yet?
I know you've been busy with irl and the frontend rework, so I never asked and just waited, but by now I am curious if there are any updates regarding this or if it is eventually already possible.

Best regards ^-^

**Comment by AuroraLS3** [comment]
I looked at this but since it was a lot larger than a few lines of code I had to skip it (Since I only had time for small changes)

I figured out a way to do this though - A lot of the queries use `WHERE server_uuid=$1` so I'll be able to change it to `WHERE $1 IS NULL OR server_uuid=$1` to have data for all servers take into account without duplicating every query
