### ISSUE TITLE
Make it so Plan dosent halt the speed of the server starting

### ISSUE THREAD

**Issue by dymrrr** [plan-player-analytics/Plan#2356]
### I would like to be able to..

[06:57:31 INFO]: [Plan] Loading server identifying information takes up 20 seconds of my boot time. My server boots up in less than 15 seconds and it takes me 50 seconds now due to the loading thing. **Suggestion: ** What if, the server identifying information happens after the startup of the server? Like everyone can play and stuff and in the background, it loads the server identifiying information.

### Is your feature request related to a problem? Please describe.

No

**Comment by TomLewis** [comment]
Most likley due to the recent mySQL update?

**Comment by AuroraLS3** [comment]
Here's what's going on

- Plan starts up and queues all database preparation stuff (table creation, index creation, schema patching)
  - During this preparation nothing can be queried or it might run into errors if tables or columns are missing
- The server information is loaded from database (for some reason, see asterisk*)  
- The server information loading is blocked by database getting ready for operations
- Plan can't process events before server information is available because it needs to link data to specific server (this is why it currently blocks boot)

\* There is code that is supposed to load server information from the file, but there is some bug that causes it to still wait for database

----

Why it hasn't been fixed yet:

- All the event processing logic would need to be modified so that it can wait for database and that would take a lot of work.
- There is some bug in the code that prevents the earlier fix for this from working properly
