### ISSUE TITLE
Parse luckperms prefix colors

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2374]
### Describe the issue

Luckperms prefix has some color syntax that is not parsed for display.

![example](https://user-images.githubusercontent.com/40795318/163568556-9db8bb19-4a56-4cba-969e-c95ef6b5b66c.png)

**Comment by Vankka** [comment]
The primary formats that should matter for reference (rrggbb = for hex):

#### Legacy codes [Minecraft Wiki](https://minecraft.fandom.com/wiki/Formatting_codes)  
 - `&c` / `§c` 

#### Adventure's rgb syntax [Adventure docs](https://docs.adventure.kyori.net/serializer/legacy.html#rgb-support)
 - `&#rrggbb` (Unlikely to use `§`)  

#### BungeeCord's [Adventure docs](https://docs.adventure.kyori.net/serializer/legacy.html#rgb-support)
 - `&x&r&r&g&g&b&b` (also potentially with `§` instead)  

#### MiniMessage [Adventure/MM docs](https://docs.adventure.kyori.net/minimessage/format.html#color) 
 - `<`_color name_`>` eg. `<red>`
   + Color names from [Minecraft wiki](https://minecraft.fandom.com/wiki/Formatting_codes#Formatting_codes)
     - With additional alises for `dark_grey` and `grey` (`a` -> `e`)
 - `<#rrggbb>`
 - `<color:`_color name_`>`
 - `<color:#rrggbb>`
 - Also `<colour:***>` with a extra `u` and `<c:***>`

Considering the complexity (especially of MiniMessage) it might be worth looking into doing using some of adventure's serializers to do the bulk of the heavy lifting, worth noting those serializer(s) *should be* relocated - but should not be relocated for sponge & velocity code since those use their platforms own serializers directly.

Also this also probably applies in a lot of places where Minecraft components are being used, not just LuckPerms prefixes. But in most other cases it should be easier to control/know in what format the input will be in.
