### ISSUE TITLE
RAM usage issues

### ISSUE THREAD

**Issue by AICentralYT** [plan-player-analytics/Plan#2662]
### Describe the issue

The ram usage is fine when players are online but has a zigzag pattern when np players are online, even though Linux says otherwise.
[https://morehybridhosting.xyz/images/Ram-usage-issue.png](url)

### Exceptions & Other Logs

```

```

### Plugin versions

1.18.1

**Comment by AuroraLS3** [comment]
The zig zag is memory getting used and then Java running garbage collection.

Linux doesn't show it because Java reserves a specific amount and the usage of the reserved amount doesn't change when Java uses up that reserved space.

I think the pattern looks normal since the rate of increasing memory usage is constant instead of irregular increases
