### ISSUE TITLE
html.description.noГеолокация what ?

### ISSUE THREAD

**Issue by dwdsty** [plan-player-analytics/Plan#2799]
https://imgur.com/a/nuDFUXN

**Comment by AuroraLS3** [comment]
The translation system of the old web files is still interfering with the new one in some places where words happen to match the ones in Javascript.

In this case plugin locale is set as RU and the old translation system replaced the word 'Geolocations' in the translation identifier for html.description.noGeolocations and the new system didn't find the proper translation because of that.

The description is supposed to say that Geolocations are disabled due to config or due to failure downloading the geolite2 database.

These sort of issues will go away once the old web files are removed from the plugin.
