### ISSUE TITLE
New plugins support for additional data source

### ISSUE THREAD

**Issue by koval01** [plan-player-analytics/Plan#2914]
### I would like to be able to..

I suggest you add support for [CoreProtect](https://www.spigotmc.org/resources/coreprotect.8631/), [AuxProtect](https://www.spigotmc.org/resources/auxprotect.99147/) and [LimboAuth](https://github.com/Elytrium/LimboAuth).

### Is your feature request related to a problem? Please describe.

There seem to be no problems. Just need new features.

**Comment by AuroraLS3** [comment]
Please open a plug in suggestion ticket for the last two https://github.com/plan-player-analytics/Plan/issues/new?assignees=&labels=New+Data%2CDataExtensions%2CHelp+Wanted&template=plugin_request.yml

Core protect support was attempted at one point, but unfortunately their API fetches all blocks into memory. This is problematic when world edits show up, since an innocent data query from Plan could try to load millions and millions of blocks into memory, causing server to crash with out of memory
