### ISSUE TITLE
Player Friend Groups

### ISSUE THREAD

**Issue by QarthO** [plan-player-analytics/Plan#3005]
### I would like to be able to..

Track friend groups. 
Basically it would try to predict if players were friends or not.
It would look at sessions of the players and see which players have similar sessions.
It would look at player locations, see if the players are commonly within x amount of blocks. (probably could be a curve, and more complicated than just this, ie smaller the x more likely, larger  less likely)

### Is your feature request related to a problem? Please describe.

Super useful insight to track friend groups. 
Could also use this data to suggest if players are getting along or playing solo.
Could use this to suggest if players are joining from our advertising, or from their friends inviting them.
If certain friend groups are causing problems, leading to easier moderation. ie, tempban an entire friend group.

I feel like this just opens the door to super useful moderation and insights.

**Comment by Scot-Survivor** [comment]
+1, 
this kind of heuristic tracking would be well cool. 

It would be helpful for marketing, the more prominent groups you can give more attention to and trust their advice more.

Or flip it, you wonder why some people aren't socialising as much & try to fix that

Would be a great way to track community engagement.

**Comment by AuroraLS3** [comment]
I ran into this kind of clustering analysis while I was writing my Bachelor's thesis. There's a way to cluster traces to see which people move together, but as always with clustering, the algorithms are quite expensive to run.

It would definitely be interesting and useful, but I see some problems with potential solutions for this:

### Solution 1: Gather player distance between online players at time intervals

This will produce `0.5 * n * (n - 1)` dimensional time-series data. (https://math.stackexchange.com/a/154948) where n is amount of players online at a given time. 
So with 50 players online, 1225 line graphs would be produced. Even at 5 minute intervals that is 14700 datapoints stored per hour (compared to 60 for TPS and 3000 for ping with 50 players. 

Servers have been reporting that they are struggling with the size of the ping data already, and some have disabled the gathering of that data. That means it might be unfeasible to store this data for long enough to produce meaningful information out of it.

### Solution 2: Store location of players at time intervals

This basically leaves the distance calculation to be done later, and with 50 players would store 3000 data points at similar size as ping data.
Challenges with analyzing spatial data such as coordinates is that it often requires spatial indexing (Splitting point space in half multiple times so that binary search is possible within coordinate system). MySQL or SQLite do not support this kind of thing out of the box as far as I know, and Postgres requires installing extensions. 

This solution would rely on either clustering algorithms or calculating distance between all player pairs later, though I imagine that would be more expensive than clustering.

### Solution 3: Session overlap analysis

It sounds very simple to check if two players are playing at the same time often, but the bruteforce algorithm for checking all session pairs takes at least `0.5 * n * (n - 1)` checks. This means that at 500k sessions you need to check `124 999 750 000` different combinations to see which sessions overlap. As you can imagine this might be a bit slow to execute.

I think one way around this would be to use the ping data or a different time series data (timestamp, user_id) to see who was online at a given time. Ping data gathering has several delays before it starts gathering so it might be too imprecise to tell who was online at the same time.

### Summary

This is definitely a problem that can be solved, but it either requires a lot of storage space, or lot of computational resources. As such I am tempted to mark this as out of scope, but I'll keep it open for some time in case some discussion emerges.

**Comment by Scot-Survivor** [comment]
Given the 3 dimensional time series data that's produced, 3,000 points doesn't seem all that much. Surely you could vectorise the operations on this array to prevent it completely choking the cpu?

**Comment by AuroraLS3** [comment]
If you go with solution 2 you need to have some spatial operations supported by the database, since in 30 days at 3000 points/h it's 2 160 000 points of data in 30d (for a single server), and loading all that to memory would take at least 345 MB + overhead of memory (3 32bit ints, 1 64bit long-timestamp). (Loading to memory would be necessary if database doesn't support spatial operations like distance calculation)

**Comment by Scot-Survivor** [comment]
Ahhh I see, I can see why there's issues with it now. 🤔

**Comment by QarthO** [comment]
I read through the issues this problem presents and I agree fully that it will be expensive. 

Solution 2 and Solution 3 seem the best fit as both calculations can be done later to prevent cutting into the server's performance.

Solution 3 is based on sessions and all of that data is already stored currently with Plan. Another solution to build onto this is not to store any more data. Just have it when you select a player there's a button to run the player session cluster analysis only relative to that specific player. Looking at your example of 50 players, selecting 1 player, would only result in 49 pairs. You wouldn't be performing any calculations on the pairs that the selected player isn't a part of. This would significantly reduce the expense in terms of performance. The resulting cluster analysis doesn't even have to be stored if we're worried about storage expenses. (I still think it should be stored, by maybe an opt-in save button after the analysis is complete)

The above can also be applied to Solution 2, where we're only analyzing the selected player. However, this would require more information to be stored such as player location every interval. As a result, this could be an opt-in. Making sure it's highly configurable such as the interval duration, only keeping past x locations per player, etc.

Obviously, with this method, you're only getting clusters relative to a specific player and not the server player base as a whole. However, I believe this could be a good stepping stone in the right direction until what seems like an impossible problem is solved.

**Comment by Scot-Survivor** [comment]
There is a mistake with your comment on solution 3, in order to run the cluster analysis, just doing it on one player won't be beneficial surely, because it can't show you any "likely" friends?

**Comment by QarthO** [comment]
You're comparing 1 player to every other player. It's not just 1 player. So 49 comparisons. The difference is you're only doing this 49 times once. Not 49 times per player.
You wouldn't be able to tell if his "likely" friends are friends. But friends with the original selected player would be calculated

**Comment by Scot-Survivor** [comment]
Oooh yes you see your point now. 

Yeah this could work then.

**Comment by Scot-Survivor** [comment]
@AuroraLS3 Do you have resources for this kind of clustering to be ran? / What its called. 
Its something I'm interested in general.

**Comment by AuroraLS3** [comment]
Usually location based clustering analysis is designed in Geographic Information System (GIS) such as ArcGIS and then the specific algorithms used can be found/implemented for whatever programming language you're using https://www.esri.com/en-us/what-is-gis/overview
Postgres has a GIS extension called postgis that supports basic spatial operations such as distance, within-radius etc, and indexing

I remember trying out some Java based clustering program at one point but I've unfortunately misplaced that since it didn't end up in the thesis.

Here's a book on Game Analytics that has a chapter on clustering https://doi.org/10.1007/978-1-4471-4769-5 - I think you can find it on Google Scholar or library
and here is a study on block placement and removal activity of players in Minecraft http://www.fdg2015.org/papers/fdg2015\_paper\_39.pdf

**Comment by AuroraLS3** [comment]
Here's some bonus pictures from that bachelor thesis I did on trying to find player bases using clustering
![image](https://user-images.githubusercontent.com/24460436/236833266-d464d37b-8f64-4d6c-a2a0-21742ce4ca02.png)
![image](https://user-images.githubusercontent.com/24460436/236833303-96eab692-90a2-4ebe-815a-910840e3ea46.png)
![image](https://user-images.githubusercontent.com/24460436/236833334-f40b7837-ef8c-4534-b9e6-aeebb0121e50.png)

**Comment by Scot-Survivor** [comment]
Thank you :) 

I'll continue looking into it. I appreciate the help.

**Comment by AuroraLS3** [comment]
Closing as Out of Scope
