### ISSUE TITLE
Log Players' IP Addresses

### ISSUE THREAD

**Issue by ThomasGW120** [plan-player-analytics/Plan#3049]
### I would like to be able to..

Log players' IP addresses.

### Is your feature request related to a problem? Please describe.

One of my players got banned due to cheating. I didn't ban his IP but I want to prevent him to use another account to play. If Plan can log players' addresses, I will be able to know whether the new player is someone who got banned or not.

**Comment by AuroraLS3** [comment]
I think you should be able to use a ban plug-in to ban by IP instead.

Storing all IP addresses is a can of worms, since according to GDPR IP addresses are personal data. Gathering all IPs to prevent one person from accessing is not reasonable from their point of view, since same outcome can be reached by storing the single IP address of the offender (Found in server logs) in a deny list.
