### ISSUE TITLE
Feature Request: Inactive Player Data Filtering for Player Analytics

### ISSUE THREAD

**Issue by tropicdev** [plan-player-analytics/Plan#3148]
### I would like to be able to..

I would like to request a feature within the Plan Player Analytics system that allows the dashboard and REST API to filter player data based on a setting called "Hide_inactive_player_data_after." This feature should enable the option to hide data for players who have left the server, gone inactive, or are on vacation, without removing their data from the database.

### Is your feature request related to a problem? Please describe.

As a server administrator or analytics user, it can be challenging to differentiate between active and inactive players when analyzing player data. Currently, the Plan Player Analytics system displays data for all players, including those who are no longer actively participating in the server. This can lead to misleading statistics and makes it difficult to focus on the relevant player insights.

**Comment by AuroraLS3** [comment]
Is something specific missing from the Query page where you can filter using Activity Group for all other than Inactive?

**Comment by tropicdev** [comment]
No I did not mean for the query page, it was mainly for the pages where players are being displayed in bulk (Player List Page). When a player leaves the game or becomes inactive, instead of deleting their entry, the intention is to filter out or conceal inactive players from the list. This means the list will only show players who have had recent logins, while retaining the data of inactive players for reference. By doing so, the user can easily review the active players without being overwhelmed by a large number of inactive ones.

**Comment by AuroraLS3** [comment]
Yes but it would be easier to add more functionality to the Query page which already has the functionality to filter out inactive players, rather than implement complicated queries for everything else.

![image](https://github.com/plan-player-analytics/Plan/assets/24460436/d683ef8e-2c57-4302-8865-1223a1f37459)

Query results page currently shows the playerlist, Playerbase activity graphs, geolocation map and some session information.

Would there be something more that you want to see about these players?

**Comment by tropicdev** [comment]
Ahm no. Thanks
