### ISSUE TITLE
Suspected Memory Leak [Potentially caused by DDoS]

### ISSUE THREAD

**Issue by KingJustin123** [plan-player-analytics/Plan#3486]
### Describe the issue

Having recently installed a clean install of Plan Across my network, I've noticed that my proxy server, which is a sufficiently powerful machine with 3 dedicated cores and 6GB of Memory, is having severe performance issues, as memory utilisation hits maximum whenever anyone tries to login to the PLAN page, my proxy without plan averages at only 300mb of utilisation when Plan is disabled.

### Exceptions & Other Logs

```

```

### Plugin versions

Plan Version: 5.6 Build 2731
Server Jar: Velocity 3.3.0-SNAPSHOT (git-74c932e5-b363)

### Additional information
- Have tried another clean install of PLAN, does not seem to rectify the issue.

**Comment by AuroraLS3** [comment]
Please send a crash log with OutOfMemoryError and a heap dump of crash to verify what is taking memory - add this flag to your server startup command to generate a heap dump on OutOfMemoryError `java -XX:+HeapDumpOnOutOfMemoryError`

Please note that if there is no such error it is normal Java behavior since Java will use all allocated memory and then perform Garbage Collection to free some of it for reuse.

**Comment by KingJustin123** [comment]
I've attached a link to the heap dump, the issue is the proxy is freezing up, so this summary was pulled right before the system froze up.

https://spark.lucko.me/Z3EGPvioA8

I'm trying to get more debug info for you but obviously, its hard to do that with the proxy freezing up and not crashing out.

**Comment by AuroraLS3** [comment]
I modified the transaction in question to be skipped if there's 500 in the queue, this should limit the impact of a DDoS on memory. A build will appear here https://github.com/plan-player-analytics/Plan/actions/runs/8061548560

**Comment by AuroraLS3** [comment]
You can also enabled `Webserver.Security.Access_log.Print_to_console` setting to see the incoming requests on console and block the IP from your firewall

**Comment by KingJustin123** [comment]
Hi Aurora, I've followed these steps, the issue still persists, so I contacted my hosting provider, who checked and could see no abnormal traffic on the network. 

As a precautionary step, I changed the SSL certificate settings to the in-built certificate, rather then proxy mode, this has stopped the memory maxing out, obviously this isn't ideal as I'd like to be able to enable the login, if theres a way you could rate-limit the connection in question that would be great

**Comment by AuroraLS3** [comment]
I have added a simple rate-limiting guard in this build https://github.com/plan-player-analytics/Plan/actions/runs/8077220127

This should prevent simple DDoS that doesn't follow redirects (Which this DDoS seems to be doing) - Since you're using proxy-mode I would guess this is a simple ddos program running that looks for any HTTP webserver and then starts hitting the / path repeatedly.

I also prevented the access logging transaction for requests blocked by this to save resources if it is a DDoS attack.

It allows 30 requests / 2 minutes to same path (e.g. `/`) after which the connection will start to be rate limited.

Regular users won't ever hit this rate limiter.

----

I would still try look at the request logs using the Plan setting in addition of relying on your host provider to monitor traffic, just so that you have hard data to look at.

**Comment by AuroraLS3** [comment]
It's pretty impressive how that 800 MB heap dump managed to make Eclipse Memory Analyzer generate a whopping **30 GB** report.html file when trying to analyze the leak objects (I only noticed just now when temp file cleanup found 60 GB of temp files - there were 2 of these report.html files)
