### ISSUE TITLE
Database server not even recognized?

### ISSUE THREAD

**Issue by dchu096** [plan-player-analytics/Plan#3538]
### Describe the issue

Hey! So i have a database server, and you can see the IP right there
![image](https://github.com/plan-player-analytics/Plan/assets/39256422/54dd2c9f-c1f6-4d51-b578-f29da084298a)
and its input correctly in PLAN config
![image](https://github.com/plan-player-analytics/Plan/assets/39256422/930b0042-ce1a-4410-b790-9147045a4519)
and its trying to point to my localhost IP instead
![image](https://github.com/plan-player-analytics/Plan/assets/39256422/1e775168-9f21-4013-bfa2-98c04413ee7c)

### Exceptions & Other Logs

N/A - folder empty

```

```

### Plugin versions

5.6 build 2820

### Additional information

Tested with another IP, its showing up correctly but just this ip isnt for some reason, i dont think its a problem from linode? Other plugins manages to connect correctly, just plan doesnt.

**Comment by AuroraLS3** [comment]
The mysql user may lack privileges to the specific database

**Comment by dchu096** [comment]
Hello! It may seems like a misconfiguration, but the database user have full access, so there shouldn't be any privilege error. 

Note I also tried using the same credentials on another plugin with plan and it seems like there's no problem, but when I try to use it with plan it just refuses to work.

And also tried swapping IP too and didn't help, thanks!

**Comment by AuroraLS3** [comment]
If you use public IP address you need to grant privileges to external IP addresses since the traffic will route outside the machine before it reaches mysql. This may help https://pterodactyl.io/tutorials/mysql_setup.html#allowing-external-database-access

Please also make sure that a database used in Database.Mysql.Database setting exists and the privileges have been granted for that database. Other plug-ins may work if they're using a different database name.

**Comment by AuroraLS3** [comment]
Also check that the mysql port is open on the firewall and reachable with same details as in Plan configure from your own machine. You can do this with a client like HeidiSQL

**Comment by dchu096** [comment]
Hello! I perfectly tested it with mysql workbench and its accessible, the database user is % so it should be accessible, and mariadb is already on port 0.0.0.0, also do please note that PLAN (and another one) is the only plugin having this issue.

**Comment by AuroraLS3** [comment]
Could you send a screenshot of the database list in your mysql, the database name from the Plan config, and screenshot of mysql workbench users and privileges tab https://dev.mysql.com/doc/workbench/en/wb-mysql-connections-navigator-management-users-and-privileges.html

I am asking this since there are 2700 servers running Plan with mysql - the chances are that there is something in your setup that is unique which is causing the issue

**Comment by AuroraLS3** [comment]
If it's not privileges it can be a networking issue, which is unlikely since you can access it through mysql workbecnch

**Comment by dchu096** [comment]
Yeah sure, I will update you tomorrow. Tho I was thinking of that as well, cuz I've setup plan multiple times before, the only thing different from previous times is I used linode instead of vultr, but I really don't think that should matter tho :(

**Comment by AuroraLS3** [comment]
Is linode using kubernetes? That could add some extra networking that's needed if the minecraft pod is separate from the mysql pod

**Comment by dchu096** [comment]
Hey! Yep, i found the issue in the end, for some reason it is the IP being weird, asked linode support to swap it and now it turns out working again! 🤔 

Oh well. Thanks tho!
