### ISSUE TITLE
The data download is very, very long

### ISSUE THREAD

**Issue by notikj** [plan-player-analytics/Plan#3661]
### Describe the issue
Downloading data one way or another: Reviewing the player base, Player Retention, Player List, Geolocation and Making a request take a very long time to load. The download may take a couple of minutes.

### Plugin versions
Plan 5.6 build 2883

### Additional information

Tell me, please, how can I speed up the data download? https://imgur.com/a/F97qtIJ

**Comment by AuroraLS3** [comment]
Check that your computer clock is synchronized with NTP https://github.com/plan-player-analytics/Plan/discussions/2389

If that doesn't help, please give some more information, like how many players you have in the database or how long you have had Plan installed

**Comment by notikj** [comment]
> Check that your computer clock is synchronized with NTP #2389
> 
> If that doesn't help, please give some more information, like how many players you have in the database or how long you have had Plan installed

Plan has been installed for more than a year, there are 500 thousand players in the database

**Comment by AuroraLS3** [comment]
Your amount of data is more than what the database in use can handle. Queries usually start being slow around 2 million sessions due to the amount of data.

You can either delete data (using the Time Thresholds settings in Plan config) or get a more powerful database instance.

**Comment by jtJava** [comment]
I am at 1 million session after 2 months of use and I am having this same issue, however, my database instance isn't even close to saturating max CPU power (AMD R5 5600X) unless MySQL is single-threaded.
![image](https://github.com/user-attachments/assets/69e277f8-be1e-4f81-96c3-d5921e6729e4

Errors like below appear in the database container:
`
2024-07-25  2:25:17 50 [Warning] Aborted connection 50 to db: 'plan_database' user: 'plan' host: '127.0.0.1' (Got timeout reading communication packets)
2024-07-25  2:25:40 58 [Warning] Aborted connection 58 to db: 'plan_database' user: 'plan' host: '127.0.0.1' (Got timeout reading communication packets)
2024-07-25  2:25:40 59 [Warning] Aborted connection 59 to db: 'plan_database' user: 'plan' host: '127.0.0.1' (Got timeout reading communication packets)
2024-07-25  2:25:40 60 [Warning] Aborted connection 60 to db: 'plan_database' user: 'plan' host: '127.0.0.1' (Got timeout reading communication packets)
2024-07-25  2:25:41 61 [Warning] Aborted connection 61 to db: 'plan_database' user: 'plan' host: '127.0.0.1' (Got timeout reading communication packets)

`

**Comment by AuroraLS3** [comment]
I'm not sure what the connection abort messages mean - there is hikaricp connection pool in use which takes care of idle connections.

As for optimizing, it's very difficult. I got a similar size dataset for optimization purposes and unfortunately the query explanations in mysql are difficult to interpret.

The most expensive queries connect data from multiple sources via joins and while I've managed to optimize some things, the slow requests are doing quite difficult things.

Playerbase and player list calculate the data based on Activity index, which union selects last 3 weeks from plan_sessions for each player to calculate it. This seems to get very expensive with many sessions.

Geolocations table has a poor schema in that it stores multiple Geolocation, date, user_id rows per user, so to show them on a map you need to get the latest one for each player. While there are multiple ways to do this, joining the table to itself comparing dates is the fastest one I've found, and unfortunately if you have a lot of data to go through less-than comparison is not very efficient.

I'd change the schema, but that would leave Java 8 users behind, since the schema was changed right before Java 11 update just to get something solid enough to work with while keeping that Java 8 version able to store data in the same database. Obviously it'll have to be dropped at some point, but I was hoping to at least get a lightweight Java 8 Plan client that transmits the data through HTTP to a main webserver. That dream is still quite far away and my resources for development are quite limited.
