### ISSUE TITLE
RCON Setup 

### ISSUE THREAD

**Issue by K3llerk1nd98** [plan-player-analytics/Plan#3737]
### I would like to be able to..

Hey together,

would nice, if there could be some way, to configure some RCON-setup if needed, to gain console-access if you want to.

but already such a lovely peace of software!!! amazing work you´ve done here!

### Is your feature request related to a problem? Please describe.

no

**Comment by AuroraLS3** [comment]
This is out of scope for the plugin since it is not a server management tool. 

Adding any server management features would lead to requests for further management tools such as file management and doing that sort of thing through a server plugin is not adequate since you can't manage plugin jars through the system that's running them
