### ISSUE TITLE
I would like to add an automatic restart button on the web page and be able to monitor the use of threads in the plugin list in real time

### ISSUE THREAD

**Issue by yuankun1** [plan-player-analytics/Plan#3787]
### I would like to be able to..

I hope you can refer to the plug-in here
https://www.spigotmc.org/resources/nekomaid.106359/

### Is your feature request related to a problem? Please describe.

So we can restart remotely
This way we can check which plug-in is delaying the card thread
Performance detection is then added to a list of plug-ins that can be monitored using latency and some event delay calls

**Comment by AuroraLS3** [comment]
Server reboot is out of the scope for this plugin, because Plan is not and never will be server management software. It is easier to have server management software be the one that starts servers rather than something that is started by the server. (Also plugins can only shutdown a server so reboot would not be possible to guarantee)

I can unfortunately not look into how Nekomaid does their detection, because their license (AGPL) is incompatible with license of Plan (LGPL) - Including any code from their plugin would require relicensing Plan to AGPL and I don't wish to do so.

In my opinion you should use Spark for profiling server thread issues https://spark.lucko.me/download - they have already implemented a system way better than I could for that sort of thing.
