### ISSUE TITLE
Activity index stuck at 3.04

### ISSUE THREAD

**Issue by lucas2107** [plan-player-analytics/Plan#603]
----

**Description of the issue**

All players who are active and reach 3.04 in activity index are stuck: http://prntscr.com/js5i3b

**Comment by Rsl1122** [comment]
What are your values for activity in the config?

**Comment by lucas2107** [comment]
PlaytimeThreshold: 240
        LoginThreshold: 3

**Comment by Rsl1122** [comment]
If your Plan install is less than 3 weeks old that reduces activity indexes from the maximum.

In order to have index of 5 (max) the player has to play 4x threshold playtime all 3 weeks - With your settings that is 16 hours per week for the last 3 weeks.

I'm currently refactoring the data representations in the plugin, so I'll see what I can do to make the index more accurate for newer installs when I'm working on that part.
