### ISSUE TITLE
[Feature Request] OPT OUT / IN from storing personal data

### ISSUE THREAD

**Issue by Morsmorse** [plan-player-analytics/Plan#621]
A opt out command for users so that the plugin doesn't store personal data about that user anymore. But still Data like general amount of users, online times etc. but just not related to a specific user/ip/uuid.

Or (which would be more compliant with the gdpr probably) that the plugin asks a player on first join if they allow the storage of personal data. If the user doesn't agree its just processing anonymised data and if yes it's processing data like now.

Or that the admin can turn of the logging of personal data like IPs / usernames / UUIDs in general and just statistic data is stored and not data about a specific user. (average players etc.)

(I hope thats understandable :D )

**Comment by Rsl1122** [comment]
Clarification on the HIGH complexity

### Currently not storing personal data

#### IP Anonymization

IPs are currently anonymized for every user by hashing them, so according to GDPR Plan data is *pseudonymized*. (That is, not linkable to a real person without outside data)

#### UUIDs/Player Names

General consensus on the spigot forums seems to be that UUIDs/Player names & related data are not personal data, so gathering game metadata is allowed - otherwise every single thing on the server would need to ask for permission. (For example, locking a chest or giving a user a plot, even storing permissions)

And if they are personal data, the player (or their guardian) gives the permission during registration of the account.

### Possible changes:

There are two options for the Opt-out and I'm still debating which one is the best option.

- Hash UUIDs (Hashing makes things readable one way, so original UUID is required to get the hash, this is how IPs are stored)
- Opt-out (Pseudonymization)
  - Anonymize names & remove nickname information
  - Deny visibility of opped out user's page
  - Keep collecting all data
- Opt-out (No gathering)
  - Remove player's data
  - Deny visibility of opped out user's page
- Opt-in
  - Add name back in
  - Allow visibility of opped out user's page
- Config setting for Opt-in-first basis, default value false (This is only possible if the Opt-out option is Pseudonymization)
- Database value for opped-out

#### Not true anonymization

Unfortunately this will not be true anonymization, but further pseudonymization, since an extra UUID from an outside source can be used to obtain a reference to the data.

This makes me wonder how useful this even is.

True anonymization would require the thought from the very beginning of the project. If Plan were to truly anonymize the data it would be clumped under a single user that would cause all analysis to be unreliable.

**Plan relies on identifiers heavily** during it's per-player (think averages) analysis and true anonymization would break that. (think a single user "Anonymized users" being a large outlier in the average value)
It is not possible to gather data about someone without any identifiers, so a one way hash is the best option if the data is to be gathered.

**Comment by Rsl1122** [comment]
> Maybe opt out (or in) would be easier with a permission (would probably need the implementation of a external permission plugin?)

It's a lot easier to have a variable in the Plan database than having an external permission system dependency.

> a random, anonymous name is stored and no ip etc. (like anon001 etc.?).

This is how I was going to do it. *Anonymize names & remove nickname information* -> Anon#32 (ID from Plan db)
IP addresses are already anonymized.

The data still needs some identifier so that the data can be even gathered (Player joins, how do we know which spot to put his data in? -> UUID)

----

> Just denying access & keeping on logging data is most likely not compliant with the gdpr.

Clarification the "keep collecting all data": Collect data that is anonymous, eg everything but Nicknames, username, IPs.

Plan does not store personal data (Other than hashed IPs) so this is compliant with the GDPR. (Usernames & UUIDs are not personal data)

Keep in mind that all server logs contain UUIDs, IPs (Less anonymous than Plan) and player names anyway when they connect. Due to the IPs the server logs **are** considered personal data under GDPR (More so than Plan data).

**Comment by Morsmorse** [comment]
Oh, okay thanks for the clarifications :) 


> Keep in mind that all server logs contain UUIDs, IPs (Less anonymous than Plan) and player names anyway when they connect. Due to the IPs the server logs are considered personal data under GDPR (More so than Plan data).

I know, we delete them regularly if we don't need them anymore.

**Comment by Rsl1122** [comment]
This issue seems to have fallen on the floor of the workshop.

As of 5.0 Plan no longer stores IP addresses of users, and so no personal data is stored.

An Opt-out / in feature is still viable (for whole data-gathering) - If the feature is still desirable please open a new issue for a data-gathering opt-out/in feature.
