### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by MicleBrick** [plan-player-analytics/Plan#739]
[Velocity](https://www.velocitypowered.com/) is a growing alternative to BungeeCord. It has a good API similar to Sponge's API (some Sponge people also help develop it), so I imagine it'd be somewhere between Plan's Bungee and Sponge implementations. The API has enough features currently to implement Plan on I think, so my suggestion is adding a velocity implementation of Plan

**Comment by Rsl1122** [comment]
If you feel like testing here is a test version that should support velocity
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.5.0-DEV1

**Comment by Miclebrick** [comment]
Have you considered relocations?

**Comment by Magi1053** [comment]
I got plan working on Velocity by injecting the JDBC into my classpath
https://forums.velocitypowered.com/t/220/4
However, I am having trouble connecting my sponge and bukkit servers to it. Following the wiki, the command should be `/plan m setup <address>`, but when I attempt this I get the following error:
```Connection succeeded, but Receiving server was not a Bungee server. Use Bungee address instead.```
What command should I be using to connect my servers to Velocity?

**Comment by Rsl1122** [comment]
I'll try to get this for next bugfix version - the command is correct, but the plugin locale is simply outdated as everything states "Bungee" instead of "Bungee / Velocity"

The error likely occurs because the address given to the command points to the server you're trying to connect (Sponge / Bukkit)

**Comment by Magi1053** [comment]
Does this fix the issue connecting servers to velocity when it's expecting bungee?

**Comment by Rsl1122** [comment]
The language files have been changed to say Proxy instead of Bungee (To avoid confusion about the issue being about not being on Bungee).
Plan has not expected Bungee since commit 14584065fb6a61205a17ab88fbdbe16d03ac0250 - The error message in your earlier comment is shown when the setup command sends a request to a Bukkit or Sponge server. @Magi1053

**Comment by Magi1053** [comment]
Still not able to get this working. As you know before it was giving the error
```Connection succeeded, but Receiving server was not a Bungee server. Use Bungee address instead.```

Now it is giving this error when trying to connect my Bukkit server to Velocity:
```Connection succeeded, but Receiving server was a Bukkit or Sponge server. Use another address instead.```

Additionally, there is still this tiny little bit of language that is asking for a `BungeeAddress`
![image](https://user-images.githubusercontent.com/1045179/61099563-657f4f00-a428-11e9-9315-ad38377f56e8.png)
