### ISSUE TITLE
Custom access levels

### ISSUE THREAD

**Issue by HotProtato** [plan-player-analytics/Plan#986]
You should make it so a list of custom access levels can be made and permissions can be assigned to them in the configuration and what pages they may access. Have webuser creation and management be the same though. Having a new permission to make IP addresses visible would also be nice for IP history. Keep up the good work.

**Comment by Rsl1122** [comment]
Some notes that shine light on the `p: 50` tag, even though this issue appears simple.

> You should make it so a list of custom access levels can be made and permissions can be assigned to them in the configuration and what pages they may access

Since the web users are in the database, they are shared between all servers in the network. If the permissions are stored in the config one server might not know what permissions a certain group has.

This means that a different kind of solution that stores the information in database is required for similar functionality.

> Having a new permission to make IP addresses visible would also be nice for IP history

Current system doesn't allow partial display of things based on access permissions (Since the cache only stores one version of each page, and the rendering code doesn't know who is viewing the page)

This could be overcome by changing how the pages are rendered. Since there is an upcoming redesign of the web panel, I have decided to add JSON + Javascript rendering to the mix, making this possible after the redesign.

----

Estimate: It will take a while before this issue will be worked on.

**Comment by Rsl1122** [comment]
I feel like access levels are a bad solution, but the alternative is implementing a custom permission system into Plan. That seems like a lot of work and that's why this issue is too big in scope to be worked on. Perhaps if the authentication gets a revisit one day.

I'm closing this issue though, if you would like to see an authentication rework, please open a new issue.
