### ISSUE TITLE
[Feature Request] Playerbase Development with more timeline option

### ISSUE THREAD

**Issue by Tiplish** [plan-player-analytics/Plan#989]
Hi ! 

I would like to have more option to manage the timeline in Playerbase Development section. 

Indeed, for example in "player activity", we could change the timeline to have last 24 hours or 30 days or more. It could be very usefull to have a large view of the evolution of our player base.

Thanks :)

**Comment by Rsl1122** [comment]
Hello. I'm sorry, but this is not possible due to technical limitations of the used chart library. 

The playerbase development graph is a *stack graph* while the players online graphs are *line graphs*.

The line graphs are drawn using HighStock, and stack graphs are drawn using HighCharts.

HighCharts does not have an option for the time selectors and HighStock does not have stack graphs.

If they add such a feature though, this would be one of the first things.

**Comment by Tiplish** [comment]
Is there another way to see the evolution of the player base? For example a line graphs with the evolution of the playerbase including by default the population between regular and very active activity? It will be very usefull to have an estimation of the evolution of the player base thanks to implementation/event/comunnication campagn etc...

**Comment by Rsl1122** [comment]
I have made a suggestion to HighCharts forum.

https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/37276144-stack-graphs-to-highstock

I'll let you know in this issue if they ever add such feature, it might take a long time.

**Comment by Rsl1122** [comment]
With the current implementation, best bet is exporting server html and then copying a version every 3 months.

Line graph is possible to implement, but it does not get the relative sizes or amount of total players across

**Comment by Tiplish** [comment]
Ok, thanks for your fast answer and : You plugin is awesome to have a global view ;) It really helps to manage large server
